In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import tf_keras as tfk
import gensim.downloader as api
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tf_keras import models as md
from tf_keras import layers as ly
from tf_keras import losses as ls
from tf_keras import optimizers as oz
from tf_keras import metrics as ms
import numpy as np
import tensorflow as tf
# import drive
# import files
# from datasets import Dataset
from transformers import (BertTokenizerFast, TFBertTokenizer, BertTokenizer, RobertaTokenizerFast,
                          DataCollatorWithPadding, TFRobertaForSequenceClassification, TFBertForSequenceClassification,
                          TFBertModel, create_optimizer)
import torch, pathlib, os, re, string, time
from torch import tensor
import pandas as pd
import transformers as trf
from transformers import AutoConfig

from google.colab import drive

import accelerate
from tf_keras.src.losses import kl_divergence
from transformers import Trainer, TrainingArguments
from tf_keras.src.optimizers.adam import Adam

import pickle

from tf_keras.src.optimizers.schedules.learning_rate_schedule import CosineDecay

import torch
from torch.utils.data import TensorDataset

In [ ]:
import pandas as pd
dataset2 = pd.read_parquet(r"/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet(r"/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

cdataset2 = dataset2
dataset2_text = dataset2["text"].tolist()
dataset3_text = dataset3["text"].tolist()
cdataset3 = dataset3
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig

tokenizer = BertTokenizerFast.from_pretrained(model_max_length=1024, pretrained_model_name_or_path='bert-base-uncased')
config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
tdataset2_text = tokenizer(dataset2_text, padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3_text, padding=True, truncation=True, max_length=128)
tdataset2_dict = tdataset2_text.data
tdataset3_dict = tdataset3_text.data
cTdataset2 = pd.DataFrame.from_dict(tdataset2_dict)

cdataset2 = pd.concat([cdataset2, cTdataset2], axis=1)
tokenized_dataset2 = cdataset2

cTdataset3 = pd.DataFrame.from_dict(tdataset3_dict)

cdataset3 = pd.concat([cdataset3, cTdataset3], axis=1)
tokenized_dataset3 = cdataset3

print(cdataset2.shape)
print(cdataset2.columns)
print(len(cdataset2['input_ids']), len(cdataset2['token_type_ids']), len(cdataset2['attention_mask']), len(cdataset2['label']))
print(cdataset3.shape)
print(cdataset3.columns)
print(len(cdataset3['input_ids']), len(cdataset3['token_type_ids']), len(cdataset3['attention_mask']), len(cdataset3['label']))

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

(9543, 5)
Index(['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'], dtype='object')
9543 9543 9543 9543
(2388, 5)
Index(['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'], dtype='object')
2388 2388 2388 2388

In [ ]:
BATCH_SIZE=8
numeric_feature_names2 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features2 = tokenized_dataset2[numeric_feature_names2]

numeric_feature_names3 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features3 = tokenized_dataset3[numeric_feature_names3]

nf2l = numeric_features2["label"].values.tolist()
nf3l = numeric_features3["label"].values.tolist()
labels2 = torch.tensor(nf2l)
labels3 = torch.tensor(nf3l)

print(labels2.shape, labels2.size())
print(labels3.shape, labels3.size())

import torch.nn.utils.rnn as rnn


# Pad the lists to a fixed length
max_length = 128  # adjust this to the maximum length of your lists
padded_numeric_features2_id = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['input_ids']],
                                               batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_id = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['input_ids']],
                                               batch_first=True)  # , maxlen=max_length)
padded_numeric_features2_ids = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['token_type_ids']],
                                                batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_ids = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['token_type_ids']],
                                                batch_first=True)  # , maxlen=max_length)
padded_numeric_features2_mask = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['attention_mask']],
                                                 batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_mask = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['attention_mask']],
                                                 batch_first=True)  # , maxlen=max_length)
# Convert the padded tensors to PyTorch tensors
import torch.nn.functional as F

padded_numeric_features2_id = F.pad(padded_numeric_features2_id, (0, max_length - padded_numeric_features2_id.shape[1]))
padded_numeric_features3_id = F.pad(padded_numeric_features3_id, (0, max_length - padded_numeric_features3_id.shape[1]))
padded_numeric_features2_ids = F.pad(padded_numeric_features2_ids,
                                     (0, max_length - padded_numeric_features2_ids.shape[1]))
padded_numeric_features3_ids = F.pad(padded_numeric_features3_ids,
                                     (0, max_length - padded_numeric_features3_ids.shape[1]))
padded_numeric_features2_mask = F.pad(padded_numeric_features2_mask,
                                      (0, max_length - padded_numeric_features2_mask.shape[1]))
padded_numeric_features3_mask = F.pad(padded_numeric_features3_mask,
                                      (0, max_length - padded_numeric_features3_mask.shape[1]))


print(padded_numeric_features2_id.shape, padded_numeric_features2_ids.shape, padded_numeric_features2_mask.shape, labels2.shape)
print(padded_numeric_features3_id.size(), padded_numeric_features3_ids.size(), padded_numeric_features3_mask.size(), labels3.size())
#print(tensor_dataset3.get_shape())

#tensor_dataset3 = TensorDataset(padded_numeric_features3_id, padded_numeric_features3_ids, padded_numeric_features3_mask, labels3)
#print(tensor_dataset3['input_ids'].size(), tensor_dataset3['token_type_ids'].size(), tensor_dataset3['attention_mask'].size(), tensor_dataset3['label'].size())
#print(tensor_dataset3.get_shape())

from torch.utils.data import DataLoader

tensor_dataset3 = TensorDataset(padded_numeric_features3_id, padded_numeric_features3_ids, padded_numeric_features3_mask, labels3)

data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE)



# Get the shape and size of each tensor in the dataset
print(tensor_dataset3.tensors[0].shape)  # shape of padded_numeric_features3_id
print(tensor_dataset3.tensors[0].size())  # size of padded_numeric_features3_id

print(tensor_dataset3.tensors[1].shape)  # shape of padded_numeric_features3_ids
print(tensor_dataset3.tensors[1].size())  # size of padded_numeric_features3_ids

print(tensor_dataset3.tensors[2].shape)  # shape of padded_numeric_features3_mask
print(tensor_dataset3.tensors[2].size())  # size of padded_numeric_features3_mask

print(tensor_dataset3.tensors[3].shape)  # shape of labels3
print(tensor_dataset3.tensors[3].size())  # size of labels3
# Create a pandas DataFrame from the DataLoader
df3 = pd.DataFrame([batch for batch in data_loader3])

# Assign column names
df3.columns = ['input_ids', 'token_type_ids', 'attention_mask', 'label']

torch.Size([9543]) torch.Size([9543])
torch.Size([2388]) torch.Size([2388])
torch.Size([9543, 128]) torch.Size([9543, 128]) torch.Size([9543, 128]) torch.Size([9543])
torch.Size([2388, 128]) torch.Size([2388, 128]) torch.Size([2388, 128]) torch.Size([2388])
torch.Size([2388, 128])
torch.Size([2388, 128])
torch.Size([2388, 128])
torch.Size([2388, 128])
torch.Size([2388, 128])
torch.Size([2388, 128])
torch.Size([2388])
torch.Size([2388])

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

#print(len(labels2), len(input_ids2), len(attention_mask2), len(token_type_ids2))
print(len(labels3), len(padded_numeric_features3_id), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask))

class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels
        self.field_names = ['input_ids', 'token_type_ids', 'attention_mask', 'labels']

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }


# Assuming df is your pandas DataFrame
input_ids3 = [tensor for tensor in df3['input_ids']]
token_type_ids3 = [tensor for tensor in df3['token_type_ids']]
attention_mask3 = [tensor for tensor in df3['attention_mask']]
labels3 = df3['label'].values

#print(input_ids3.shape, token_type_ids3.shape, padded_numeric_features3_ids.shape, padded_numeric_features3_mask.shape, len(labels3))
print(len(input_ids3), len(token_type_ids3), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask), len(labels3))


try:
    datasetxxx3 = CustomTensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)
    data_loaderxx3 = DataLoader(datasetxxx3, batch_size=8, shuffle=True)
except Exception as e:
    print(f"Error creating datasetxxx3: {e}")

tensor_dataset2 = TensorDataset(padded_numeric_features2_id, padded_numeric_features2_ids,
                                padded_numeric_features2_mask, labels2)
from torch.utils.data import DataLoader

data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE)

299 2388 2388 2388
299 299 2388 2388 299

In [ ]:
# Create a pandas DataFrame from the DataLoader
df2 = pd.DataFrame([batch for batch in data_loader2])

# Assign column names
df2.columns = ['input_ids', 'token_type_ids', 'attention_mask', 'label']

import torch
from torch.utils.data import Dataset, DataLoader


class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels
        self.field_names = ['input_ids', 'token_type_ids', 'attention_mask', 'labels']

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }


# Assuming df is your pandas DataFrame
input_ids2 = [tensor for tensor in df2['input_ids']]
token_type_ids2 = [tensor for tensor in df2['token_type_ids']]
attention_mask2 = [tensor for tensor in df2['attention_mask']]
labels2 = df2['label'].values

#print(input_ids3.shape, token_type_ids3.shape, padded_numeric_features3_ids.shape, padded_numeric_features3_mask.shape, len(labels3))
print(len(input_ids2), len(token_type_ids2), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask), len(labels2))

try:
    datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
    data_loaderxx2 = DataLoader(datasetxxx2, batch_size=8, shuffle=True)
except Exception as e:
    print(f"Error creating datasetxxx2: {e}")

"""
datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)

# Create a DataLoader from the custom dataset
data_loaderxx2 = DataLoader(datasetxxx2, batch_size=8, shuffle=True)"""

print(df2.shape, df2.columns)
print(df3.shape, df3.columns)

1193 1193 2388 2388 1193
(1193, 4) Index(['input_ids', 'token_type_ids', 'attention_mask', 'label'], dtype='object')
(299, 4) Index(['input_ids', 'token_type_ids', 'attention_mask', 'label'], dtype='object')

In [ ]:
# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased',num_labels=1)
# model = AutoModelForSequenceClassification.from_scratch(num_labels=1)
# model = AutoModelForSequenceClassification(config=AutoConfig(num_labels=1))

# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased', num_labels=1)

config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
config.num_labels = 1

model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False

model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True
"""

print(len(input_ids2), len(token_type_ids2), len(attention_mask2), len(labels2))
datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
"""
from transformers import TrainingArguments, Trainer
import torch
import torch.nn as nn
import torch.nn.functional as F

1193 1193 1193 1193

In [ ]:
import pandas as pd
dataset2 = pd.read_parquet(r"/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet(r"/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")
print(dataset2.shape)
print(dataset2.columns)
print(len(dataset2['input_ids']), len(dataset2['token_type_ids']), len(dataset2['attention_mask']), len(dataset2['label']))
print(dataset3.shape)
print(dataset3.columns)
print(len(dataset3['input_ids']), len(dataset3['token_type_ids']), len(dataset3['attention_mask']), len(dataset3['label']))

(9543, 2)
Index(['text', 'label'], dtype='object')

KeyError: 'input_ids'

In [ ]:


# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased',num_labels=1)
# model = AutoModelForSequenceClassification.from_scratch(num_labels=1)
# model = AutoModelForSequenceClassification(config=AutoConfig(num_labels=1))

# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased', num_labels=1)

config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
config.num_labels = 1

model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False

model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True

"""
print(len(input_ids2), len(token_type_ids2), len(attention_mask2), len(labels2))
datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
"""
from transformers import TrainingArguments, Trainer
import torch
import torch.nn as nn
import torch.nn.functional as F

Mounted at /content/drive

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

299 299 299 1193

In [ ]:


# ===============================================================================================================================

# from transformers import AutoModelForImageClassification, MobileNetV2Config, MobileNetV2ForImageClassification

training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    # total # of training epochs
    # prediction_loss_only=compute_loss,
    per_device_train_batch_size=8,  # batch size
    # per device during training
    per_device_eval_batch_size=8,  # batch size for evaluation
    warmup_steps=500,  # number of warmup steps for learning rate scheduler
    weight_decay=0.01,
)
"""
num_labels = len(processed_datasets["train"].features["labels"].names)

# initialize models
teacher_model = AutoModelForImageClassification.from_pretrained(
    "merve/beans-vit-224",
    num_labels=num_labels,
    ignore_mismatched_sizes=True
)

# training MobileNetV2 from scratch
student_config = MobileNetV2Config()
student_config.num_labels = num_labels
student_model = MobileNetV2ForImageClassification(student_config)"""
# =============================================================================================================================
"""
#old code
def get_logits(inputs):
    teacher_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
    student_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
    teacher_logits = model(**teacher_inputs).logits
    student_logits = model(**student_inputs).logits
    return teacher_logits, student_logits

def compute_loss(model, inputs):
    teacher_logits, student_logits = get_logits(inputs)
    loss = distillation_loss(teacher_logits, student_logits)
    return loss

def distillation_loss(teacher_logits, student_logits, temperature=10.0):
    teacher_probs = tf.nn.softmax(teacher_logits / temperature, axis=-1)
    student_probs = tf.nn.softmax(student_logits / temperature, axis=-1)
    return kl_divergence()(teacher_probs, student_probs)
"""
num_epochs = 3
batches_per_epoch = 1  # 227(1821)[07196]69170,8
total_train_steps = int(batches_per_epoch * num_epochs)
# optimizer = Adam(init_lr=2e-5)#, num_warmup_steps=0, num_train_steps=total_train_steps)
optimizer = Adam()
scheduler = CosineDecay(initial_learning_rate=2e-5, decay_steps=total_train_steps)
"""
training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",  # output directory
    num_train_epochs=3,  # total # of training epochs
    prediction_loss_only=compute_loss,
    per_device_train_batch_size=8,  # batch size
    # per device during training
    per_device_eval_batch_size=8,  # batch size for evaluation
    warmup_steps=500,  # number of warmup steps for learning rate scheduler
    weight_decay=0.01,  # strength of weight decay
    logging_dir=r"/content/drive/MyDrive",  # directory for storing logs
)"""
####
from transformers import DataCollatorWithPadding, DataCollator
"""
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, train_dataset=None, eval_dataset=None, temperature=None, compute_metrics=None,  *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher_model = model
        self.student_model = model
        #self.loss_function = nn.KLDivLoss(reduction="batchmean")
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.teacher.to(device)
        self.teacher.eval()
        self.temperature = temperature
		#model=model,  # the model to be trained
		#args=training_args,  # training arguments
		self.train_dataset=train_dataset,  # training dataset
		self.eval_dataset=eval_dataset,  # evaluation dataset
		compute_metrics=compute_metrics
"""

import torch
from transformers import AutoModelForSequenceClassification, AutoConfig, TrainingArguments, Trainer
from torch.utils.data import Dataset, DataLoader
"""
# Define the custom dataset class
class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }
"""

# Define the custom data collator function
def custom_data_collator(features):
    input_ids = torch.tensor([f['input_ids'] for f in features])
    token_type_ids = torch.tensor([f['token_type_ids'] for f in features])
    attention_mask = torch.tensor([f['attention_mask'] for f in features])
    labels = torch.tensor([f['labels'] for f in features])

    return {
        'input_ids': input_ids,
        'token_type_ids': token_type_ids,
        'attention_mask': attention_mask,
        'labels': labels
    }

# Define the ImageDistilTrainer class
"""
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model, teacher_model, train_dataset, eval_dataset, temperature, compute_metrics, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.student = student_model
        self.train_dataset = train_dataset
        self.eval_dataset = eval_dataset
        self.temperature = temperature
        self.compute_metrics = compute_metrics

    def get_logits(self, inputs):
        teacher_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        student_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        teacher_logits = self.teacher(**teacher_inputs).logits
        student_logits = self.student(**student_inputs).logits
        return teacher_logits, student_logits

    def distillation_loss(self, teacher_logits, student_logits):
        teacher_probs = torch.nn.functional.softmax(teacher_logits / self.temperature, axis=-1)
        student_probs = torch.nn.functional.softmax(student_logits / self.temperature, axis=-1)
        return torch.nn.KLDivLoss(reduction="batchmean")(teacher_probs, student_probs)

    def compute_loss(self, model, inputs):
        teacher_logits, student_logits = self.get_logits(inputs)
        loss = self.distillation_loss(teacher_logits, student_logits)
        return loss
"""
# Define the training arguments
training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    #num_train_epochs
	  num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
)

# Load the pre-trained BERT model and tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
config = AutoConfig.from_pretrained('bert-base-uncased')
config.num_labels = 1
model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False
model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True

# Create the custom datasets and data loaders
datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
datasetxxx3 = CustomTensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)
data_loaderxx2 = DataLoader(datasetxxx2, batch_size=8, shuffle=True)
data_loaderxx3 = DataLoader(datasetxxx3, batch_size=8, shuffle=True)

# Create the ImageDistilTrainer instance
trainer = ImageDistilTrainer(
    student_model=model,
    teacher_model=model,
    train_dataset=datasetxxx2,
    eval_dataset=datasetxxx3,
    data_collator=custom_data_collator,
    compute_metrics=lambda pred: {'accuracy': torch.sum(pred.label_ids == pred.predictions.argmax(-1))},
    temperature=10,
)

# Train the model
trainer.train()
"""
trainer = ImageDistilTrainer(
    student_model=model,
    teacher_model=model,
    args=training_args,
    train_dataset=datasetxxx2,
    eval_dataset=datasetxxx3,
   # data_collator=data_collator,
    compute_metrics=lambda pred: {'accuracy': tf.metrics.accuracy(pred.label_ids, pred.predictions.argmax(-1))},
    temperature=5
)
# Create a Trainer instance
"""
"""
trainer = Trainer(
    model=model,  # the model to be trained
    args=training_args,  # training arguments
    train_dataset=datasetxxx2,  # training dataset
    eval_dataset=datasetxxx3,  # evaluation dataset
    compute_metrics=lambda pred: {'accuracy': tf.metrics.accuracy(pred.label_ids, pred.predictions.argmax(-1))},
    # serialization='pickle'#compute_loss=compute_loss#(model, inputs)
)
"""

In [ ]:


# ===============================================================================================================================

# from transformers import AutoModelForImageClassification, MobileNetV2Config, MobileNetV2ForImageClassification

training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    # total # of training epochs
    # prediction_loss_only=compute_loss,
    per_device_train_batch_size=8,  # batch size
    # per device during training
    per_device_eval_batch_size=8,  # batch size for evaluation
    warmup_steps=500,  # number of warmup steps for learning rate scheduler
    weight_decay=0.01,
)

# =============================================================================================================================

num_epochs = 3
batches_per_epoch = 1  # 227(1821)[07196]69170,8
total_train_steps = int(batches_per_epoch * num_epochs)
# optimizer = Adam(init_lr=2e-5)#, num_warmup_steps=0, num_train_steps=total_train_steps)
optimizer = Adam()
scheduler = CosineDecay(initial_learning_rate=2e-5, decay_steps=total_train_steps)

####
from transformers import DataCollatorWithPadding, DataCollator


import torch
from transformers import AutoModelForSequenceClassification, AutoConfig, TrainingArguments, Trainer
from torch.utils.data import Dataset, DataLoader


# Define the custom data collator function
def custom_data_collator(features):
    input_ids = torch.tensor([f['input_ids'] for f in features])
    token_type_ids = torch.tensor([f['token_type_ids'] for f in features])
    attention_mask = torch.tensor([f['attention_mask'] for f in features])
    labels = torch.tensor([f['labels'] for f in features])

    return {
        'input_ids': input_ids,
        'token_type_ids': token_type_ids,
        'attention_mask': attention_mask,
        'labels': labels
    }

# Define the ImageDistilTrainer class

# Define the training arguments
training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    #num_train_epochs
	  num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
)

# Load the pre-trained BERT model and tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
config = AutoConfig.from_pretrained('bert-base-uncased')
config.num_labels = 1
model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False
model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True

# Create the custom datasets and data loaders
datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
datasetxxx3 = CustomTensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)
data_loaderxx2 = DataLoader(datasetxxx2, batch_size=8, shuffle=True)
data_loaderxx3 = DataLoader(datasetxxx3, batch_size=8, shuffle=True)

# Create the ImageDistilTrainer instance
trainer = ImageDistilTrainer(
    student_model=model,
    teacher_model=model,
    train_dataset=datasetxxx2,
    eval_dataset=datasetxxx3,
    data_collator=custom_data_collator,
    compute_metrics=lambda pred: {'accuracy': torch.sum(pred.label_ids == pred.predictions.argmax(-1))},
    temperature=10,
)

# Train the model
trainer.train()

In [ ]:

class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, train_dataset=None, eval_dataset=None, temperature=None, compute_metrics=None, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.student = student_model
        # self.loss_function = nn.KLDivLoss(reduction="batchmean")
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.teacher.to(device)
        self.teacher.eval()
        self.temperature = temperature
        #teacher_model = teacher_model,  # the model to be trained
        #student_model=student_model,
        #args = training_args,  # training arguments
        self.train_dataset = train_dataset,  # training dataset
        self.eval_dataset = eval_dataset,  # evaluation dataset
        self.compute_metrics = compute_metrics


    def get_logits(inputs):
        teacher_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        student_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        teacher_logits = teacher_model(**teacher_inputs).logits
        student_logits = student_model(**student_inputs).logits
        return teacher_logits, student_logits


    def distillation_loss(teacher_logits, student_logits, temperature=10.0):
        teacher_probs = tf.nn.softmax(teacher_logits / temperature, axis=-1)
        student_probs = tf.nn.softmax(student_logits / temperature, axis=-1)
        return kl_divergence()(teacher_probs, student_probs)


    def compute_loss(model, inputs):
        teacher_logits, student_logits = get_logits(inputs)
        loss = distillation_loss(teacher_logits, student_logits)
        return loss

In [ ]:
import tf_keras as tfk
import gensim.downloader as api
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tf_keras import models as md
from tf_keras import layers as ly
from tf_keras import losses as ls
from tf_keras import optimizers as oz
from tf_keras import metrics as ms
import numpy as np
import tensorflow as tf
# import drive
# import files
# from datasets import Dataset
from transformers import (BertTokenizerFast, TFBertTokenizer, BertTokenizer, RobertaTokenizerFast,
                          DataCollatorWithPadding, TFRobertaForSequenceClassification, TFBertForSequenceClassification,
                          TFBertModel, create_optimizer)
import torch, pathlib, os, re, string, time
from torch import tensor
import pandas as pd
import transformers as trf
from transformers import AutoConfig

from google.colab import drive

import accelerate
from tf_keras.src.losses import kl_divergence
from transformers import Trainer, TrainingArguments
from tf_keras.src.optimizers.adam import Adam

import pickle

from tf_keras.src.optimizers.schedules.learning_rate_schedule import CosineDecay

import torch
from torch.utils.data import TensorDataset

drive.mount('/content/drive')

BATCH_SIZE = 8
dataset2 = pd.read_parquet(r"/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet(r"/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")
cdataset2 = dataset2
dataset2_text = dataset2["text"].tolist()
dataset3_text = dataset3["text"].tolist()
cdataset3 = dataset3
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig

tokenizer = BertTokenizerFast.from_pretrained(model_max_length=1024, pretrained_model_name_or_path='bert-base-uncased')
config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
tdataset2_text = tokenizer(dataset2_text, padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3_text, padding=True, truncation=True, max_length=128)
tdataset2_dict = tdataset2_text.data
tdataset3_dict = tdataset3_text.data
cTdataset2 = pd.DataFrame.from_dict(tdataset2_dict)

cdataset2 = pd.concat([cdataset2, cTdataset2], axis=1)
tokenized_dataset2 = cdataset2

cTdataset3 = pd.DataFrame.from_dict(tdataset3_dict)

cdataset3 = pd.concat([cdataset3, cTdataset3], axis=1)
tokenized_dataset3 = cdataset3

numeric_feature_names2 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features2 = tokenized_dataset2[numeric_feature_names2]

numeric_feature_names3 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features3 = tokenized_dataset3[numeric_feature_names3]

nf2l = numeric_features2["label"].values.tolist()
nf3l = numeric_features3["label"].values.tolist()
labels2 = torch.tensor(nf2l)
labels3 = torch.tensor(nf3l)

import torch.nn.utils.rnn as rnn

# Pad the lists to a fixed length
max_length = 128  # adjust this to the maximum length of your lists
padded_numeric_features2_id = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['input_ids']],
                                               batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_id = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['input_ids']],
                                               batch_first=True)  # , maxlen=max_length)
padded_numeric_features2_ids = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['token_type_ids']],
                                                batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_ids = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['token_type_ids']],
                                                batch_first=True)  # , maxlen=max_length)
padded_numeric_features2_mask = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['attention_mask']],
                                                 batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_mask = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['attention_mask']],
                                                 batch_first=True)  # , maxlen=max_length)
# Convert the padded tensors to PyTorch tensors
import torch.nn.functional as F

padded_numeric_features2_id = F.pad(padded_numeric_features2_id, (0, max_length - padded_numeric_features2_id.shape[1]))
padded_numeric_features3_id = F.pad(padded_numeric_features3_id, (0, max_length - padded_numeric_features3_id.shape[1]))
padded_numeric_features2_ids = F.pad(padded_numeric_features2_ids,
                                     (0, max_length - padded_numeric_features2_ids.shape[1]))
padded_numeric_features3_ids = F.pad(padded_numeric_features3_ids,
                                     (0, max_length - padded_numeric_features3_ids.shape[1]))
padded_numeric_features2_mask = F.pad(padded_numeric_features2_mask,
                                      (0, max_length - padded_numeric_features2_mask.shape[1]))
padded_numeric_features3_mask = F.pad(padded_numeric_features3_mask,
                                      (0, max_length - padded_numeric_features3_mask.shape[1]))

tensor_dataset3 = TensorDataset(padded_numeric_features3_id, padded_numeric_features3_ids,
                                padded_numeric_features3_mask, labels3)
from torch.utils.data import DataLoader

data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE)

# Create a pandas DataFrame from the DataLoader
df3 = pd.DataFrame([batch for batch in data_loader3])

# Assign column names
df3.columns = ['input_ids', 'token_type_ids', 'attention_mask', 'label']

import torch
from torch.utils.data import Dataset, DataLoader


class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels
        self.field_names = ['input_ids', 'token_type_ids', 'attention_mask', 'labels']

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }


# Assuming df is your pandas DataFrame
input_ids3 = [tensor for tensor in df3['input_ids']]
token_type_ids3 = [tensor for tensor in df3['token_type_ids']]
attention_mask3 = [tensor for tensor in df3['attention_mask']]
labels3 = df3['label'].values

datasetxxx3 = CustomTensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create a DataLoader from the custom dataset
data_loaderxx3 = DataLoader(datasetxxx3, batch_size=8, shuffle=True)

tensor_dataset2 = TensorDataset(padded_numeric_features2_id, padded_numeric_features2_ids,
                                padded_numeric_features2_mask, labels2)
from torch.utils.data import DataLoader

data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE)

# Create a pandas DataFrame from the DataLoader
df2 = pd.DataFrame([batch for batch in data_loader2])

# Assign column names
df2.columns = ['input_ids', 'token_type_ids', 'attention_mask', 'label']

import torch
from torch.utils.data import Dataset, DataLoader


class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels
        self.field_names = ['input_ids', 'token_type_ids', 'attention_mask', 'labels']

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }


# Assuming df is your pandas DataFrame
input_ids2 = [tensor for tensor in df3['input_ids']]
token_type_ids2 = [tensor for tensor in df3['token_type_ids']]
attention_mask2 = [tensor for tensor in df3['attention_mask']]
labels2 = df2['label'].values

datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)

# Create a DataLoader from the custom dataset
data_loaderxx2 = DataLoader(datasetxxx2, batch_size=8, shuffle=True)

# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased',num_labels=1)
# model = AutoModelForSequenceClassification.from_scratch(num_labels=1)
# model = AutoModelForSequenceClassification(config=AutoConfig(num_labels=1))

# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased', num_labels=1)

config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
config.num_labels = 1

model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False

model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True

from transformers import TrainingArguments, Trainer
import torch
import torch.nn as nn
import torch.nn.functional as F

#== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==

class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, train_dataset=None, eval_dataset=None, temperature=None, compute_metrics=None, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.student = student_model
        # self.loss_function = nn.KLDivLoss(reduction="batchmean")
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.teacher.to(device)
        self.teacher.eval()
        self.temperature = temperature
        #teacher_model = teacher_model,  # the model to be trained
        #student_model=student_model,
        #args = training_args,  # training arguments
        self.train_dataset = train_dataset,  # training dataset
        self.eval_dataset = eval_dataset,  # evaluation dataset
        self.compute_metrics = compute_metrics


    def get_logits(inputs):
        teacher_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        student_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        teacher_logits = teacher_model(**teacher_inputs).logits
        student_logits = student_model(**student_inputs).logits
        return teacher_logits, student_logits


    def distillation_loss(teacher_logits, student_logits, temperature=10.0):
        teacher_probs = tf.nn.softmax(teacher_logits / temperature, axis=-1)
        student_probs = tf.nn.softmax(student_logits / temperature, axis=-1)
        return kl_divergence()(teacher_probs, student_probs)


    def compute_loss(model, inputs):
        teacher_logits, student_logits = get_logits(inputs)
        loss = distillation_loss(teacher_logits, student_logits)
        return loss


# ===============================================================================================================================

# from transformers import AutoModelForImageClassification, MobileNetV2Config, MobileNetV2ForImageClassification

training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    # total # of training epochs
    # prediction_loss_only=compute_loss,
    per_device_train_batch_size=8,  # batch size
    # per device during training
    per_device_eval_batch_size=8,  # batch size for evaluation
    warmup_steps=500,  # number of warmup steps for learning rate scheduler
    weight_decay=0.01,
)
"""
num_labels = len(processed_datasets["train"].features["labels"].names)

# initialize models
teacher_model = AutoModelForImageClassification.from_pretrained(
    "merve/beans-vit-224",
    num_labels=num_labels,
    ignore_mismatched_sizes=True
)

# training MobileNetV2 from scratch
student_config = MobileNetV2Config()
student_config.num_labels = num_labels
student_model = MobileNetV2ForImageClassification(student_config)"""
# =============================================================================================================================
"""
#old code
def get_logits(inputs):
    teacher_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
    student_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
    teacher_logits = model(**teacher_inputs).logits
    student_logits = model(**student_inputs).logits
    return teacher_logits, student_logits

def compute_loss(model, inputs):
    teacher_logits, student_logits = get_logits(inputs)
    loss = distillation_loss(teacher_logits, student_logits)
    return loss

def distillation_loss(teacher_logits, student_logits, temperature=10.0):
    teacher_probs = tf.nn.softmax(teacher_logits / temperature, axis=-1)
    student_probs = tf.nn.softmax(student_logits / temperature, axis=-1)
    return kl_divergence()(teacher_probs, student_probs)
"""
num_epochs = 3
batches_per_epoch = 1  # 227(1821)[07196]69170,8
total_train_steps = int(batches_per_epoch * num_epochs)
# optimizer = Adam(init_lr=2e-5)#, num_warmup_steps=0, num_train_steps=total_train_steps)
optimizer = Adam()
scheduler = CosineDecay(initial_learning_rate=2e-5, decay_steps=total_train_steps)
"""
training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",  # output directory
    num_train_epochs=3,  # total # of training epochs
    prediction_loss_only=compute_loss,
    per_device_train_batch_size=8,  # batch size
    # per device during training
    per_device_eval_batch_size=8,  # batch size for evaluation
    warmup_steps=500,  # number of warmup steps for learning rate scheduler
    weight_decay=0.01,  # strength of weight decay
    logging_dir=r"/content/drive/MyDrive",  # directory for storing logs
)"""
####
from transformers import DataCollatorWithPadding, DataCollator
"""
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, train_dataset=None, eval_dataset=None, temperature=None, compute_metrics=None,  *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher_model = model
        self.student_model = model
        #self.loss_function = nn.KLDivLoss(reduction="batchmean")
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.teacher.to(device)
        self.teacher.eval()
        self.temperature = temperature
		#model=model,  # the model to be trained
		#args=training_args,  # training arguments
		self.train_dataset=train_dataset,  # training dataset
		self.eval_dataset=eval_dataset,  # evaluation dataset
		compute_metrics=compute_metrics
"""

import torch
from transformers import AutoModelForSequenceClassification, AutoConfig, TrainingArguments, Trainer
from torch.utils.data import Dataset, DataLoader

# Define the custom dataset class
class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }

# Define the custom data collator function
def custom_data_collator(features):
    input_ids = torch.tensor([f['input_ids'] for f in features])
    token_type_ids = torch.tensor([f['token_type_ids'] for f in features])
    attention_mask = torch.tensor([f['attention_mask'] for f in features])
    labels = torch.tensor([f['labels'] for f in features])

    return {
        'input_ids': input_ids,
        'token_type_ids': token_type_ids,
        'attention_mask': attention_mask,
        'labels': labels
    }

# Define the ImageDistilTrainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model, teacher_model, train_dataset, eval_dataset, temperature, compute_metrics, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.student = student_model
        self.train_dataset = train_dataset
        self.eval_dataset = eval_dataset
        self.temperature = temperature
        self.compute_metrics = compute_metrics

    def get_logits(self, inputs):
        teacher_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        student_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        teacher_logits = self.teacher(**teacher_inputs).logits
        student_logits = self.student(**student_inputs).logits
        return teacher_logits, student_logits

    def distillation_loss(self, teacher_logits, student_logits):
        teacher_probs = torch.nn.functional.softmax(teacher_logits / self.temperature, axis=-1)
        student_probs = torch.nn.functional.softmax(student_logits / self.temperature, axis=-1)
        return torch.nn.KLDivLoss(reduction="batchmean")(teacher_probs, student_probs)

    def compute_loss(self, model, inputs):
        teacher_logits, student_logits = self.get_logits(inputs)
        loss = self.distillation_loss(teacher_logits, student_logits)
        return loss

# Define the training arguments
training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    #num_train_epochs
	num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
)

# Load the pre-trained BERT model and tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
config = AutoConfig.from_pretrained('bert-base-uncased')
config.num_labels = 1
model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False
model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True

# Create the custom datasets and data loaders
datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
datasetxxx3 = CustomTensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)
data_loaderxx2 = DataLoader(datasetxxx2, batch_size=8, shuffle=True)
data_loaderxx3 = DataLoader(datasetxxx3, batch_size=8, shuffle=True)

# Create the ImageDistilTrainer instance
trainer = ImageDistilTrainer(
    student_model=model,
    teacher_model=model,
    train_dataset=datasetxxx2,
    eval_dataset=datasetxxx3,
    data_collator=custom_data_collator,
    compute_metrics=lambda pred: {'accuracy': torch.sum(pred.label_ids == pred.predictions.argmax(-1))},
    temperature=10,
)

# Train the model
trainer.train()
"""
trainer = ImageDistilTrainer(
    student_model=model,
    teacher_model=model,
    args=training_args,
    train_dataset=datasetxxx2,
    eval_dataset=datasetxxx3,
   # data_collator=data_collator,
    compute_metrics=lambda pred: {'accuracy': tf.metrics.accuracy(pred.label_ids, pred.predictions.argmax(-1))},
    temperature=5
)
# Create a Trainer instance
"""
"""
trainer = Trainer(
    model=model,  # the model to be trained
    args=training_args,  # training arguments
    train_dataset=datasetxxx2,  # training dataset
    eval_dataset=datasetxxx3,  # evaluation dataset
    compute_metrics=lambda pred: {'accuracy': tf.metrics.accuracy(pred.label_ids, pred.predictions.argmax(-1))},
    # serialization='pickle'#compute_loss=compute_loss#(model, inputs)
)
"""

In [ ]:
print(type(padded_numeric_features3_id), type(padded_numeric_features3_ids), type(padded_numeric_features3_mask), type(labels3))

<class 'torch.Tensor'> <class 'torch.Tensor'> <class 'torch.Tensor'> <class 'numpy.ndarray'>

In [ ]:
print(type(labels3))

<class 'numpy.ndarray'>

In [ ]:
print(type(padded_numeric_features3_mask))

<class 'torch.Tensor'>

In [ ]:
labels3_tensor = torch.stack([torch.from_numpy(tensor) for tensor in labels3])
print(labels3_tensor)

TypeError: expected np.ndarray (got Tensor)

In [ ]:
max_size = max(tensor.size(0) for tensor in labels3)
padded_tensors = []
for tensor in labels3:
    size_diff = max_size - tensor.size(0)
    padded_tensor = torch.nn.functional.pad(tensor, (0, size_diff))
    padded_tensors.append(padded_tensor)

labels3_tensor = torch.stack(padded_tensors)

In [ ]:
import tf_keras as tfk
import gensim.downloader as api
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tf_keras import models as md
from tf_keras import layers as ly
from tf_keras import losses as ls
from tf_keras import optimizers as oz
from tf_keras import metrics as ms
import numpy as np
import tensorflow as tf
# import drive
# import files
# from datasets import Dataset
from transformers import (BertTokenizerFast, TFBertTokenizer, BertTokenizer, RobertaTokenizerFast,
                          DataCollatorWithPadding, TFRobertaForSequenceClassification, TFBertForSequenceClassification,
                          TFBertModel, create_optimizer)
import torch, pathlib, os, re, string, time
from torch import tensor
import pandas as pd
import transformers as trf
from transformers import AutoConfig

from google.colab import drive

import accelerate
from tf_keras.src.losses import kl_divergence
from transformers import Trainer, TrainingArguments
from tf_keras.src.optimizers.adam import Adam

import pickle

from tf_keras.src.optimizers.schedules.learning_rate_schedule import CosineDecay

import torch
from torch.utils.data import TensorDataset


from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
dataset2 = pd.read_parquet(r"/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet(r"/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

cdataset2 = dataset2
dataset2_text = dataset2["text"].tolist()
dataset3_text = dataset3["text"].tolist()
cdataset3 = dataset3
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig

tokenizer = BertTokenizerFast.from_pretrained(model_max_length=1024, pretrained_model_name_or_path='bert-base-uncased')
config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
tdataset2_text = tokenizer(dataset2_text, padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3_text, padding=True, truncation=True, max_length=128)
tdataset2_dict = tdataset2_text.data
tdataset3_dict = tdataset3_text.data
cTdataset2 = pd.DataFrame.from_dict(tdataset2_dict)

cdataset2 = pd.concat([cdataset2, cTdataset2], axis=1)
tokenized_dataset2 = cdataset2

cTdataset3 = pd.DataFrame.from_dict(tdataset3_dict)

cdataset3 = pd.concat([cdataset3, cTdataset3], axis=1)
tokenized_dataset3 = cdataset3

print(cdataset2.shape)
print(cdataset2.columns)
print(len(cdataset2['input_ids']), len(cdataset2['token_type_ids']), len(cdataset2['attention_mask']), len(cdataset2['label']))
print(cdataset3.shape)
print(cdataset3.columns)
print(len(cdataset3['input_ids']), len(cdataset3['token_type_ids']), len(cdataset3['attention_mask']), len(cdataset3['label']))



BATCH_SIZE=8
numeric_feature_names2 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features2 = tokenized_dataset2[numeric_feature_names2]

numeric_feature_names3 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features3 = tokenized_dataset3[numeric_feature_names3]

nf2l = numeric_features2["label"].values.tolist()
nf3l = numeric_features3["label"].values.tolist()
labels2 = torch.tensor(nf2l)
labels3 = torch.tensor(nf3l)

print(labels2.shape, labels2.size())
print(labels3.shape, labels3.size())



max_size3 = max(tensor.numel() for tensor in labels3)
padded_tensors = []
for tensor in labels3:
    size_diff = max_size3 - tensor.numel()
    padded_tensor = torch.nn.functional.pad(tensor, (0, size_diff))
    padded_tensors.append(padded_tensor)

labels3_tensor = torch.stack(padded_tensors)
print(type(labels3_tensor))


max_size2 = max(tensor.numel() for tensor in labels2)
padded_tensors = []
for tensor in labels2:
    size_diff = max_size2 - tensor.numel()
    padded_tensor = torch.nn.functional.pad(tensor, (0, size_diff))
    padded_tensors.append(padded_tensor)

labels2_tensor = torch.stack(padded_tensors)
print(type(labels2_tensor))



import torch.nn.utils.rnn as rnn


# Pad the lists to a fixed length
max_length = 128  # adjust this to the maximum length of your lists
padded_numeric_features2_id = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['input_ids']],
                                               batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_id = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['input_ids']],
                                               batch_first=True)  # , maxlen=max_length)
padded_numeric_features2_ids = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['token_type_ids']],
                                                batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_ids = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['token_type_ids']],
                                                batch_first=True)  # , maxlen=max_length)
padded_numeric_features2_mask = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['attention_mask']],
                                                 batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_mask = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['attention_mask']],
                                                 batch_first=True)  # , maxlen=max_length)
# Convert the padded tensors to PyTorch tensors
import torch.nn.functional as F

padded_numeric_features2_id = F.pad(padded_numeric_features2_id, (0, max_length - padded_numeric_features2_id.shape[1]))
padded_numeric_features3_id = F.pad(padded_numeric_features3_id, (0, max_length - padded_numeric_features3_id.shape[1]))
padded_numeric_features2_ids = F.pad(padded_numeric_features2_ids,
                                     (0, max_length - padded_numeric_features2_ids.shape[1]))
padded_numeric_features3_ids = F.pad(padded_numeric_features3_ids,
                                     (0, max_length - padded_numeric_features3_ids.shape[1]))
padded_numeric_features2_mask = F.pad(padded_numeric_features2_mask,
                                      (0, max_length - padded_numeric_features2_mask.shape[1]))
padded_numeric_features3_mask = F.pad(padded_numeric_features3_mask,
                                      (0, max_length - padded_numeric_features3_mask.shape[1]))


print(padded_numeric_features2_id.shape, padded_numeric_features2_ids.shape, padded_numeric_features2_mask.shape, labels2.shape)
print(padded_numeric_features3_id.size(), padded_numeric_features3_ids.size(), padded_numeric_features3_mask.size(), labels3.size())
#print(tensor_dataset3.get_shape())

#tensor_dataset3 = TensorDataset(padded_numeric_features3_id, padded_numeric_features3_ids, padded_numeric_features3_mask, labels3)
#print(tensor_dataset3['input_ids'].size(), tensor_dataset3['token_type_ids'].size(), tensor_dataset3['attention_mask'].size(), tensor_dataset3['label'].size())
#print(tensor_dataset3.get_shape())

from torch.utils.data import DataLoader

tensor_dataset3 = TensorDataset(padded_numeric_features3_id, padded_numeric_features3_ids, padded_numeric_features3_mask, labels3_tensor)

data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE)


"""
print([label.shape, label.dtype for label in labels3])
labels3_tensors = [torch.from_numpy(label) for label in labels3]
labels3_tensor = torch.stack(labels3_tensors)
print(labels3_tensor)
"""

# Get the shape and size of each tensor in the dataset
print(tensor_dataset3.tensors[0].shape)  # shape of padded_numeric_features3_id
print(tensor_dataset3.tensors[0].size())  # size of padded_numeric_features3_id

print(tensor_dataset3.tensors[1].shape)  # shape of padded_numeric_features3_ids
print(tensor_dataset3.tensors[1].size())  # size of padded_numeric_features3_ids

print(tensor_dataset3.tensors[2].shape)  # shape of padded_numeric_features3_mask
print(tensor_dataset3.tensors[2].size())  # size of padded_numeric_features3_mask

print(tensor_dataset3.tensors[3].shape)  # shape of labels3
print(tensor_dataset3.tensors[3].size())  # size of labels3
# Create a pandas DataFrame from the DataLoader
df3 = pd.DataFrame([batch for batch in data_loader3])

# Assign column names
df3.columns = ['input_ids', 'token_type_ids', 'attention_mask', 'label']

"""
print(labels3.dtype)
labels3 = labels3.astype(np.float32)
labelx = torch.from_numpy(labels3, dtype=torch.float32)
"""


import torch
from torch.utils.data import Dataset, DataLoader

#print(len(labels2), len(input_ids2), len(attention_mask2), len(token_type_ids2))
print(len(labels3), len(padded_numeric_features3_id), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask))

class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels
        self.field_names = ['input_ids', 'token_type_ids', 'attention_mask', 'labels']

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }


# Assuming df is your pandas DataFrame
input_ids3 = [tensor for tensor in df3['input_ids']]
token_type_ids3 = [tensor for tensor in df3['token_type_ids']]
attention_mask3 = [tensor for tensor in df3['attention_mask']]
labels3_x = [tensor for tensor in df3['labels']]

#print(input_ids3.shape, token_type_ids3.shape, padded_numeric_features3_ids.shape, padded_numeric_features3_mask.shape, len(labels3_x))
print(len(input_ids3), len(token_type_ids3), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask), len(labels3_x))


try:
    datasetxxx3 = CustomTensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3_x)
    data_loaderxx3 = DataLoader(datasetxxx3, batch_size=8, shuffle=True)
except Exception as e:
    print(f"Error creating datasetxxx3: {e}")

tensor_dataset2 = TensorDataset(padded_numeric_features2_id, padded_numeric_features2_ids, padded_numeric_features2_mask, labels2_tensor)
from torch.utils.data import DataLoader

data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE)





# Create a pandas DataFrame from the DataLoader
df2 = pd.DataFrame([batch for batch in data_loader2])

# Assign column names
df2.columns = ['input_ids', 'token_type_ids', 'attention_mask', 'label']

import torch
from torch.utils.data import Dataset, DataLoader


class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels
        self.field_names = ['input_ids', 'token_type_ids', 'attention_mask', 'labels']

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }


# Assuming df is your pandas DataFrame
input_ids2 = [tensor for tensor in df2['input_ids']]
token_type_ids2 = [tensor for tensor in df2['token_type_ids']]
attention_mask2 = [tensor for tensor in df2['attention_mask']]
labels2_x = [tensor for tensor in df2['labels']]

#print(input_ids3.shape, token_type_ids3.shape, padded_numeric_features3_ids.shape, padded_numeric_features3_mask.shape, len(labels3))
print(len(input_ids2), len(token_type_ids2), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask), len(labels2))

try:
    datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2_x)
    data_loaderxx2 = DataLoader(datasetxxx2, batch_size=8, shuffle=True)
except Exception as e:
    print(f"Error creating datasetxxx2: {e}")


print(df2.shape, df2.columns)
print(df3.shape, df3.columns)


# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased',num_labels=1)
# model = AutoModelForSequenceClassification.from_scratch(num_labels=1)
# model = AutoModelForSequenceClassification(config=AutoConfig(num_labels=1))

# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased', num_labels=1)

#config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
config.num_labels = 1

model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False

model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True
from transformers import TrainingArguments, Trainer
import torch
import torch.nn as nn
import torch.nn.functional as F



class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, train_dataset=None, eval_dataset=None, temperature=None, compute_metrics=None, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.student = student_model
        # self.loss_function = nn.KLDivLoss(reduction="batchmean")
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.teacher.to(device)
        self.teacher.eval()
        self.temperature = temperature
        #teacher_model = teacher_model,  # the model to be trained
        #student_model=student_model,
        #args = training_args,  # training arguments
        self.train_dataset = train_dataset,  # training dataset
        self.eval_dataset = eval_dataset,  # evaluation dataset
        self.compute_metrics = compute_metrics


    def get_logits(inputs):
        teacher_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        student_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        teacher_logits = teacher_model(**teacher_inputs).logits
        student_logits = student_model(**student_inputs).logits
        return teacher_logits, student_logits


    def distillation_loss(teacher_logits, student_logits, temperature=10.0):
        teacher_probs = tf.nn.softmax(teacher_logits / temperature, axis=-1)
        student_probs = tf.nn.softmax(student_logits / temperature, axis=-1)
        return kl_divergence()(teacher_probs, student_probs)


    def compute_loss(model, inputs):
        teacher_logits, student_logits = get_logits(inputs)
        loss = distillation_loss(teacher_logits, student_logits)
        return loss





# ===============================================================================================================================

# from transformers import AutoModelForImageClassification, MobileNetV2Config, MobileNetV2ForImageClassification

training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    # total # of training epochs
    # prediction_loss_only=compute_loss,
    per_device_train_batch_size=8,  # batch size
    # per device during training
    per_device_eval_batch_size=8,  # batch size for evaluation
    warmup_steps=500,  # number of warmup steps for learning rate scheduler
    weight_decay=0.01,
)

# =============================================================================================================================

num_epochs = 3
batches_per_epoch = 1  # 227(1821)[07196]69170,8
total_train_steps = int(batches_per_epoch * num_epochs)
# optimizer = Adam(init_lr=2e-5)#, num_warmup_steps=0, num_train_steps=total_train_steps)
optimizer = Adam()
scheduler = CosineDecay(initial_learning_rate=2e-5, decay_steps=total_train_steps)

####
from transformers import DataCollatorWithPadding, DataCollator


import torch
from transformers import AutoModelForSequenceClassification, AutoConfig, TrainingArguments, Trainer
from torch.utils.data import Dataset, DataLoader


# Define the custom data collator function
def custom_data_collator(features):
    input_ids = torch.tensor([f['input_ids'] for f in features])
    token_type_ids = torch.tensor([f['token_type_ids'] for f in features])
    attention_mask = torch.tensor([f['attention_mask'] for f in features])
    labels = torch.tensor([f['labels'] for f in features])

    return {
        'input_ids': input_ids,
        'token_type_ids': token_type_ids,
        'attention_mask': attention_mask,
        'labels': labels
    }

# Define the ImageDistilTrainer class

# Define the training arguments
training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    #num_train_epochs
	  num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
)

# Load the pre-trained BERT model and tokenizer
#tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
"""
config = AutoConfig.from_pretrained('bert-base-uncased')
config.num_labels = 1
model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False
model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True
"""
# Create the ImageDistilTrainer instance
trainer = ImageDistilTrainer(
    student_model=model,
    teacher_model=model,
    train_dataset=datasetxxx2,
    eval_dataset=datasetxxx3,
    data_collator=custom_data_collator,
    compute_metrics=lambda pred: {'accuracy': torch.sum(pred.label_ids == pred.predictions.argmax(-1))},
    temperature=10,
)

# Train the model
trainer.train()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
(9543, 5)
Index(['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'], dtype='object')
9543 9543 9543 9543
(2388, 5)
Index(['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'], dtype='object')
2388 2388 2388 2388
torch.Size([9543]) torch.Size([9543])
torch.Size([2388]) torch.Size([2388])

RuntimeError: Padding length should be less than or equal to two times the input dimension but got padding length 2 and input of dimension 0

In [ ]:
import tf_keras as tfk
import gensim.downloader as api
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tf_keras import models as md
from tf_keras import layers as ly
from tf_keras import losses as ls
from tf_keras import optimizers as oz
from tf_keras import metrics as ms
import numpy as np
import tensorflow as tf
# import drive
# import files
# from datasets import Dataset
from transformers import (BertTokenizerFast, TFBertTokenizer, BertTokenizer, RobertaTokenizerFast,
                          DataCollatorWithPadding, TFRobertaForSequenceClassification, TFBertForSequenceClassification,
                          TFBertModel, create_optimizer)
import torch, pathlib, os, re, string, time
from torch import tensor
import pandas as pd
import transformers as trf
from transformers import AutoConfig

from google.colab import drive

import accelerate
from tf_keras.src.losses import kl_divergence
from transformers import Trainer, TrainingArguments
from tf_keras.src.optimizers.adam import Adam

import pickle

from tf_keras.src.optimizers.schedules.learning_rate_schedule import CosineDecay

import torch
from torch.utils.data import TensorDataset


from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
dataset2 = pd.read_parquet(r"/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet(r"/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

cdataset2 = dataset2
dataset2_text = dataset2["text"].tolist()
dataset3_text = dataset3["text"].tolist()
cdataset3 = dataset3
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig

tokenizer = BertTokenizerFast.from_pretrained(model_max_length=1024, pretrained_model_name_or_path='bert-base-uncased')
config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
tdataset2_text = tokenizer(dataset2_text, padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3_text, padding=True, truncation=True, max_length=128)
tdataset2_dict = tdataset2_text.data
tdataset3_dict = tdataset3_text.data
cTdataset2 = pd.DataFrame.from_dict(tdataset2_dict)

cdataset2 = pd.concat([cdataset2, cTdataset2], axis=1)
tokenized_dataset2 = cdataset2

cTdataset3 = pd.DataFrame.from_dict(tdataset3_dict)

cdataset3 = pd.concat([cdataset3, cTdataset3], axis=1)
tokenized_dataset3 = cdataset3

print(cdataset2.shape)
print(cdataset2.columns)
print(len(cdataset2['input_ids']), len(cdataset2['token_type_ids']), len(cdataset2['attention_mask']), len(cdataset2['label']))
print(cdataset3.shape)
print(cdataset3.columns)
print(len(cdataset3['input_ids']), len(cdataset3['token_type_ids']), len(cdataset3['attention_mask']), len(cdataset3['label']))



BATCH_SIZE=8
numeric_feature_names2 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features2 = tokenized_dataset2[numeric_feature_names2]

numeric_feature_names3 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features3 = tokenized_dataset3[numeric_feature_names3]

nf2l = numeric_features2["label"].values.tolist()
nf3l = numeric_features3["label"].values.tolist()
labels2 = torch.tensor(nf2l)
labels3 = torch.tensor(nf3l)

print(labels2.shape, labels2.size())
print(labels3.shape, labels3.size())

import torch.nn.utils.rnn as rnn
# Pad the tensors to the maximum length
import torch
B=labels3
# Get the maximum length of the tensors in B
#max_length = max(len(tensor) for tensor in B)
max_length=8
# Create a list to store the padded tensors
padded_tensors = []

# Iterate over the tensors in B
for tensor in B:
    # Pad the tensor to the maximum length
    maa = (len(tensor) if tensor.dim() > 0 else 0)
    padded_tensor = torch.nn.functional.pad(tensor, (0, max_length - maa))
    padded_tensors.append(padded_tensor)

# Stack the padded tensors into a single tensor
padded_tensor3 = torch.stack(padded_tensors)

print(padded_tensor3)

B2=labels2
# Get the maximum length of the tensors in B
#max_length = max(len(tensor) for tensor in B2)

# Create a list to store the padded tensors
padded_tensors = []

# Iterate over the tensors in B
for tensor in B2:
    # Pad the tensor to the maximum length
    maa = (len(tensor) if tensor.dim() > 0 else 0)
    padded_tensor = torch.nn.functional.pad(tensor, (0, max_length - maa))
    padded_tensors.append(padded_tensor)

# Stack the padded tensors into a single tensor
padded_tensor2 = torch.stack(padded_tensors)
"""
labels3_tensor = rnn.pad_sequence(labels3, batch_first=True)
labels2_tensor = rnn.pad_sequence(labels2, batch_first=True)
"""
"""
max_size3 = max(tensor.numel() for tensor in labels3)
padded_tensors = []
for tensor in labels3:
    size_diff = max_size3 - tensor.numel()
    padded_tensor = torch.nn.functional.pad(tensor, (0, size_diff))
    padded_tensors.append(padded_tensor)

labels3_tensor = torch.stack(padded_tensors)
print(type(labels3_tensor))


max_size2 = max(tensor.numel() for tensor in labels2)
padded_tensors = []
for tensor in labels2:
    size_diff = max_size2 - tensor.numel()
    padded_tensor = torch.nn.functional.pad(tensor, (0, size_diff))
    padded_tensors.append(padded_tensor)


labels2_tensor = torch.stack(padded_tensors)
print(type(labels2_tensor))"""

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
(9543, 5)
Index(['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'], dtype='object')
9543 9543 9543 9543
(2388, 5)
Index(['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'], dtype='object')
2388 2388 2388 2388
torch.Size([9543]) torch.Size([9543])
torch.Size([2388]) torch.Size([2388])

RuntimeError: Padding length should be less than or equal to two times the input dimension but got padding length 2 and input of dimension 0

In [ ]:
print(type(labels3_tensor))

<class 'torch.Tensor'>

In [ ]:
max_size = max(tensor.size(0) for tensor in labels3)
padded_tensors = []
for tensor in labels3:
    size_diff = max_size - tensor.size(0)
    padded_tensor = torch.nn.functional.pad(tensor, (0, 0, 0, size_diff))
    padded_tensors.append(padded_tensor)

labels3_tensor = torch.stack(padded_tensors)

RuntimeError: Padding length should be less than or equal to two times the input dimension but got padding length 4 and input of dimension 1

In [ ]:
max_size = max(tensor.size(0) for tensor in labels3_tensors)
padded_tensors = []
for tensor in labels3_tensors:
    size_diff = max_size - tensor.size(0)
    padded_tensor = torch.nn.functional.pad(tensor, (0, 0, 0, size_diff))
    padded_tensors.append(padded_tensor)

labels3_tensor = torch.stack(padded_tensors)

In [ ]:
print([(label.shape, label.dtype) for label in labels3])
print([type(label) for label in labels3])
labels3_tensors = [label for label in labels3]
labels3_tensor = torch.stack(labels3_tensors)
print(type(labels3_tensor))
print(labels3_tensor)

[(torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([8]), torch.int64), (torch.Size([4]), torch.int64)]
[<class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>]

RuntimeError: stack expects each tensor to be equal size, but got [8] at entry 0 and [4] at entry 298

In [ ]:
labels3_tensor = torch.stack(labels3)
print(labels3_tensor)

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not numpy.ndarray

In [ ]:
print(padded_numeric_features3_mask)

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])

In [ ]:
print(labels3)

[tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 0, 0, 0, 0, 0, 0])
 tensor([0, 1, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 0]) tensor([0, 0, 2, 0, 0, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 0]) tensor([0, 0, 1, 1, 1, 1, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 0, 0, 0, 0, 0, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 0, 0, 0, 0]) tensor([0, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 2, 2, 2, 2, 2, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 1]) tensor([1, 1, 1, 1, 1, 1, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 0]) tensor([0, 0, 0, 0, 0, 0, 0, 0])
 tensor([0, 0, 0, 0, 0, 0, 0, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor([1, 1, 1, 1, 1, 1, 1, 1])
 tensor([1, 1, 1, 2, 2, 2, 2, 2]) tensor([2, 2, 2, 2, 2, 2, 2, 2])
 tensor([2, 2, 2, 2])]

In [ ]:
print(labels3[1])

tensor([0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
print(labels3.dtype)
labelsxx = labels3.astype(np.float64)
labelx = torch.from_numpy(labelsxx, dtype=torch.float64)

object

ValueError: only one element tensors can be converted to Python scalars

In [ ]:
"""!pip install transformers
!pip install datasets
!pip install pandas
!pip install pyarrow
"""
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments, default_data_collator)

# Load the data (replace with your actual loading logic)
import pandas as pd
from datasets import load_dataset

# Example using datasets library
dataset = load_dataset('your_dataset_name', split=['train', 'validation'])

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

def preprocess_function(examples):
    return tokenizer(examples['text'], padding='max_length', truncation=True, max_length=128)

encoded_dataset = dataset.map(preprocess_function, batched=True)

# Create PyTorch datasets
tensor_dataset2 = TensorDataset(*[{'input_ids': torch.tensor(d['input_ids']),
                                   'token_type_ids': torch.tensor(d['token_type_ids']),
                                   'attention_mask': torch.tensor(d['attention_mask']),
                                   'labels': torch.tensor(d['label'])}
                                 for d in encoded_dataset['train']])
tensor_dataset3 = TensorDataset(*[{'input_ids': torch.tensor(d['input_ids']),
                                   'token_type_ids': torch.tensor(d['token_type_ids']),
                                   'attention_mask': torch.tensor(d['attention_mask']),
                                   'labels': torch.tensor(d['label'])}
                                 for d in encoded_dataset['validation']])

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)

# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature
        distillation_loss = F.kl_div(
            F.log_softmax(student_logits, dim=-1),
            F.softmax(teacher_logits, dim=-1),
            reduction="batchmean"
        )

        # Choose appropriate task loss
        if model.config.num_labels == 1:  # Binary classification or regression
            task_loss = F.binary_cross_entropy_with_logits(student_outputs.logits.squeeze(), inputs['labels'].float())
        else:  # Multi-class classification
            task_loss = F.cross_entropy(student_logits, inputs['labels'])

        loss = distillation_loss + task_loss
        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1) # Adjust num_labels
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False

# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True,
)


"""
# ... (rest of your code) ...

trainer = ImageDistilTrainer(
    # ... (other arguments) ...
    data_collator=my_data_collator,
    # ... (other arguments) ...
)"""

print(type(tensor_dataset2[1]))
print(tensor_dataset2[1])
# Initialize the Trainer
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    data_collator=None,  # Default collator works fine
    args=training_args,
    temperature=10.0,
)

# Train the model
trainer.train()

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

# Create PyTorch datasets

tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create PyTorch datasets (modified)""""
"""
tensor_dataset2 = TensorDataset(*[{'input_ids': i, 'token_type_ids': t, 'attention_mask': a, 'labels': l}
                                 for i, t, a, l in zip(input_ids2, token_type_ids2, attention_mask2, labels2)])
tensor_dataset3 = TensorDataset(*[{'input_ids': i, 'token_type_ids': t, 'attention_mask': a, 'labels': l}
                                 for i, t, a, l in zip(input_ids3, token_type_ids3, attention_mask3, labels3)])
"""
# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)


# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        #inputs = {k: v for k, v in zip(['input_ids', 'token_type_ids', 'attention_mask', 'labels'], inputs)}
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature
        loss = F.kl_div(F.log_softmax(student_logits, dim=-1), F.softmax(teacher_logits, dim=-1), reduction="batchmean")

        # Add cross-entropy loss
        loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False

from transformers import default_data_collator
"""
def torch_default_data_collator(features: List[InputDataClass]) -> Dict[str, Any]:
    import torch

    if not isinstance(features[0], Mapping):
        features = [vars(f) for f in features]
    first = features[0]
    batch = {}

    # Special handling for labels.
    # Ensure that tensor is created with the correct type
    # (it should be automatically the case, but let's make sure of it.)
    if "label" in first and first["label"] is not None:
        label = first["label"].item() if isinstance(first["label"], torch.Tensor) else first["label"]
        dtype = torch.long if isinstance(label, int) else torch.float
        batch["labels"] = torch.tensor([f["label"] for f in features], dtype=dtype)
    elif "label_ids" in first and first["label_ids"] is not None:
        if isinstance(first["label_ids"], torch.Tensor):
            batch["labels"] = torch.stack([f["label_ids"] for f in features])
        else:
            dtype = torch.long if isinstance(first["label_ids"][0], int) else torch.float
            batch["labels"] = torch.tensor([f["label_ids"] for f in features], dtype=dtype)

    # Handling of all other possible keys.
    # Again, we will use the first element to figure out which key/values are not None for this model.
    for k, v in first.items():
        if k not in ("label", "label_ids") and v is not None and not isinstance(v, str):
            if isinstance(v, torch.Tensor):
                batch[k] = torch.stack([f[k] for f in features])
            elif isinstance(v, np.ndarray):
                batch[k] = torch.tensor(np.stack([f[k] for f in features]))
            else:
                batch[k] = torch.tensor([f[k] for f in features])

    return batch
"""
from transformers import default_data_collator
def my_data_collator(features):
    # Assuming features is a list of tuples, where each tuple is (input_ids, token_type_ids, attention_mask, labels)
    processed_features = []
    for feature in features:
        processed_features.append({
            'input_ids': feature[0],
            'token_type_ids': feature[1],
            'attention_mask': feature[2],
            'labels': feature[3]
        })

    # Use the default collator to create batches of dictionaries
    return default_data_collator(processed_features)


# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True,
)


"""
# ... (rest of your code) ...

trainer = ImageDistilTrainer(
    # ... (other arguments) ...
    data_collator=my_data_collator,
    # ... (other arguments) ...
)"""

print(type(tensor_dataset2[1]))
print(tensor_dataset2[1])
# Initialize the Trainer
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    data_collator=my_data_collator,  # Default collator works fine
    args=training_args,
    temperature=10.0,
)

# Train the model
trainer.train()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

<class 'tuple'>
(tensor([  101,  1002, 10507,  2140,  1002, 22110,  2140,  1011,  2053, 16069,
         2685,  2000, 21725,  2015, 11251,  2012, 11485,  1998,  2548,  7139,
        16770,  1024,  1013,  1013,  1056,  1012,  2522,  1013,  1061,  2290,
         3501, 13876,  2475,  5596,  2509,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0]), tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), tensor(0))

TypeError: vars() argument must have __dict__ attribute

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }

# Create dataset instances
tensor_dataset2 = MyDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = MyDataset(input_ids3, token_type_ids3, attention_mask3, labels3)


# Create PyTorch datasets
#tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
#tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)


# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        #inputs = {k: v for k, v in zip(['input_ids', 'token_type_ids', 'attention_mask', 'labels'], inputs)}
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature
        loss = F.kl_div(F.log_softmax(student_logits, dim=-1), F.softmax(teacher_logits, dim=-1), reduction="batchmean")

        # Add cross-entropy loss
        loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False


# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True,
)


print(type(tensor_dataset2[1]))
print(tensor_dataset2[1])
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    args=training_args,
    temperature=10.0,
)

trainer.train()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

<class 'dict'>
{'input_ids': tensor([  101,  1002, 10507,  2140,  1002, 22110,  2140,  1011,  2053, 16069,
         2685,  2000, 21725,  2015, 11251,  2012, 11485,  1998,  2548,  7139,
        16770,  1024,  1013,  1013,  1056,  1012,  2522,  1013,  1061,  2290,
         3501, 13876,  2475,  5596,  2509,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0]), 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 'labels': tensor(0)}

IndexError: Target 2 is out of bounds.

In [ ]:
h=0

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }

# Create dataset instances
tensor_dataset2 = MyDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = MyDataset(input_ids3, token_type_ids3, attention_mask3, labels3)


# Create PyTorch datasets
#tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
#tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)


# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss using logits or predictions
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature

        # Use predictions for distillation loss if num_labels is 1
        if student_outputs.logits.shape[1] == 1:
            loss = F.kl_div(
                F.logsigmoid(student_logits.squeeze()),
                torch.sigmoid(teacher_logits.squeeze()),
                reduction="batchmean"
            )
            # For binary classification, use BCEWithLogitsLoss
            loss += F.binary_cross_entropy_with_logits(
                student_logits.squeeze(),
                inputs['labels'].float()
            )
        else:
            loss = F.kl_div(F.log_softmax(student_logits, dim=-1),
                            F.softmax(teacher_logits, dim=-1),
                            reduction="batchmean")
            # For multi-class classification, use cross_entropy
            loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False


# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="loss",
    fp16=True,
)


print(type(tensor_dataset2[1]))
print(tensor_dataset2[1])
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    args=training_args,
    temperature=10.0,
)

trainer.train()

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }

# Create dataset instances
tensor_dataset2 = MyDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = MyDataset(input_ids3, token_type_ids3, attention_mask3, labels3)


# Create PyTorch datasets
#tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
#tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)


# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss using logits or predictions
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature

        # Use predictions for distillation loss if num_labels is 1
        if student_outputs.logits.shape[1] == 1:
            loss = F.kl_div(
                F.logsigmoid(student_logits.squeeze()),
                torch.sigmoid(teacher_logits.squeeze()),
                reduction="batchmean"
            )
            # For binary classification, use BCEWithLogitsLoss
            loss += F.binary_cross_entropy_with_logits(
                student_logits.squeeze(),
                inputs['labels'].float()
            )
        else:
            loss = F.kl_div(F.log_softmax(student_logits, dim=-1),
                            F.softmax(teacher_logits, dim=-1),
                            reduction="batchmean")
            # For multi-class classification, use cross_entropy
            loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False


# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="loss",
    fp16=True,
)


print(type(tensor_dataset2[1]))
print(tensor_dataset2[1])
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    args=training_args,
    temperature=10.0,
)

trainer.train()
trainer.evaluate()

Mounted at /content/drive

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

<class 'dict'>
{'input_ids': tensor([  101,  1002, 10507,  2140,  1002, 22110,  2140,  1011,  2053, 16069,
         2685,  2000, 21725,  2015, 11251,  2012, 11485,  1998,  2548,  7139,
        16770,  1024,  1013,  1013,  1056,  1012,  2522,  1013,  1061,  2290,
         3501, 13876,  2475,  5596,  2509,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0]), 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 'labels': tensor(0)}

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }

# Create dataset instances
tensor_dataset2 = MyDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = MyDataset(input_ids3, token_type_ids3, attention_mask3, labels3)


# Create PyTorch datasets
#tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
#tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)


# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss using logits or predictions
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature

        # Use predictions for distillation loss if num_labels is 1
        if student_outputs.logits.shape[1] == 1:
            loss = F.kl_div(
                F.logsigmoid(student_logits.squeeze()),
                torch.sigmoid(teacher_logits.squeeze()),
                reduction="batchmean"
            )
            # For binary classification, use BCEWithLogitsLoss
            loss += F.binary_cross_entropy_with_logits(
                student_logits.squeeze(),
                inputs['labels'].float()
            )
        else:
            loss = F.kl_div(F.log_softmax(student_logits, dim=-1),
                            F.softmax(teacher_logits, dim=-1),
                            reduction="batchmean")
            # For multi-class classification, use cross_entropy
            loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False


# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True,
)


print(type(tensor_dataset2[1]))
print(tensor_dataset2[1])
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    args=training_args,
    temperature=10.0,
)

trainer.train()
trainer.evaluate()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

<class 'dict'>
{'input_ids': tensor([  101,  1002, 10507,  2140,  1002, 22110,  2140,  1011,  2053, 16069,
         2685,  2000, 21725,  2015, 11251,  2012, 11485,  1998,  2548,  7139,
        16770,  1024,  1013,  1013,  1056,  1012,  2522,  1013,  1061,  2290,
         3501, 13876,  2475,  5596,  2509,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0]), 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 'labels': tensor(0)}

KeyError: "The `metric_for_best_model` training argument is set to 'eval_accuracy', which is not found in the evaluation metrics. The available evaluation metrics are: ['eval_loss']. Consider changing the `metric_for_best_model` via the TrainingArguments."

In [ ]:
 import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }

# Create dataset instances
tensor_dataset2 = MyDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = MyDataset(input_ids3, token_type_ids3, attention_mask3, labels3)


# Create PyTorch datasets
#tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
#tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)


# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        #inputs = {k: v for k, v in zip(['input_ids', 'token_type_ids', 'attention_mask', 'labels'], inputs)}
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature
        loss = F.kl_div(F.log_softmax(student_logits, dim=-1), F.softmax(teacher_logits, dim=-1), reduction="batchmean")

        # Add cross-entropy loss
        loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False


# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True,
)


print(type(tensor_dataset2[1]))
print(tensor_dataset2[1]
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    args=training_args,
    temperature=10.0,
)

trainer.train()

SyntaxError: '(' was never closed (<ipython-input-20-b9e037a28ee9>, line 117)

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }

# Create dataset instances
tensor_dataset2 = MyDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = MyDataset(input_ids3, token_type_ids3, attention_mask3, labels3)


# Create PyTorch datasets
#tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
#tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)


# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        #inputs = {k: v for k, v in zip(['input_ids', 'token_type_ids', 'attention_mask', 'labels'], inputs)}
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature
        loss = F.kl_div(F.log_softmax(student_logits, dim=-1), F.softmax(teacher_logits, dim=-1), reduction="batchmean")

        # Add cross-entropy loss
        loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False


# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True,
)


print(type(tensor_dataset2[1]))
print(tensor_dataset2[1]
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    args=training_args,
    temperature=10.0,
)

trainer.train()

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

# Create PyTorch datasets
tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)


# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        #inputs = {k: v for k, v in zip(['input_ids', 'token_type_ids', 'attention_mask', 'labels'], inputs)}
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature
        loss = F.kl_div(F.log_softmax(student_logits, dim=-1), F.softmax(teacher_logits, dim=-1), reduction="batchmean")

        # Add cross-entropy loss
        loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False

from transformers import default_data_collator
"""
def torch_default_data_collator(features: List[InputDataClass]) -> Dict[str, Any]:
    import torch

    if not isinstance(features[0], Mapping):
        features = [vars(f) for f in features]
    first = features[0]
    batch = {}

    # Special handling for labels.
    # Ensure that tensor is created with the correct type
    # (it should be automatically the case, but let's make sure of it.)
    if "label" in first and first["label"] is not None:
        label = first["label"].item() if isinstance(first["label"], torch.Tensor) else first["label"]
        dtype = torch.long if isinstance(label, int) else torch.float
        batch["labels"] = torch.tensor([f["label"] for f in features], dtype=dtype)
    elif "label_ids" in first and first["label_ids"] is not None:
        if isinstance(first["label_ids"], torch.Tensor):
            batch["labels"] = torch.stack([f["label_ids"] for f in features])
        else:
            dtype = torch.long if isinstance(first["label_ids"][0], int) else torch.float
            batch["labels"] = torch.tensor([f["label_ids"] for f in features], dtype=dtype)

    # Handling of all other possible keys.
    # Again, we will use the first element to figure out which key/values are not None for this model.
    for k, v in first.items():
        if k not in ("label", "label_ids") and v is not None and not isinstance(v, str):
            if isinstance(v, torch.Tensor):
                batch[k] = torch.stack([f[k] for f in features])
            elif isinstance(v, np.ndarray):
                batch[k] = torch.tensor(np.stack([f[k] for f in features]))
            else:
                batch[k] = torch.tensor([f[k] for f in features])

    return batch
"""

def my_data_collator(features):
    # Assuming features is a list of tuples, where each tuple is (input_ids, token_type_ids, attention_mask, labels)
    processed_features = []
    for feature in features:
        processed_features.append({
            'input_ids': feature[0],
            'token_type_ids': feature[1],
            'attention_mask': feature[2],
            'labels': feature[3]
        })

    # Use the default collator to create batches of dictionaries
    return default_data_collator(processed_features)


# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True,
)


"""
# ... (rest of your code) ...

trainer = ImageDistilTrainer(
    # ... (other arguments) ...
    data_collator=my_data_collator,
    # ... (other arguments) ...
)"""

print(type(tensor_dataset2[1]))
print(tensor_dataset2[1])
# Initialize the Trainer
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    data_collator=my_data_collator,  # Default collator works fine
    args=training_args,
    temperature=10.0,
)

# Train the model
trainer.train()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

<class 'tuple'>
(tensor([  101,  1002, 10507,  2140,  1002, 22110,  2140,  1011,  2053, 16069,
         2685,  2000, 21725,  2015, 11251,  2012, 11485,  1998,  2548,  7139,
        16770,  1024,  1013,  1013,  1056,  1012,  2522,  1013,  1061,  2290,
         3501, 13876,  2475,  5596,  2509,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0]), tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), tensor(0))

AttributeError: 'str' object has no attribute 'size'

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

# Create PyTorch datasets
tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)

# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
	# Convert the input tensors to dictionaries

    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
		    inputs = {k: v for k, v in zip(['input_ids', 'token_type_ids', 'attention_mask', 'labels'], inputs)}
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature
        loss = F.kl_div(F.log_softmax(student_logits, dim=-1), F.softmax(teacher_logits, dim=-1), reduction="batchmean")

        # Add cross-entropy loss
        loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False

# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True,
)

# Initialize the Trainer
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    data_collator=None,  # Default collator works fine
    args=training_args,
    temperature=10.0,
)

# Train the model
trainer.train()

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 52)

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

# Create PyTorch datasets
tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)

# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
	# Convert the input tensors to dictionaries
    inputs = {k: v for k, v in zip(['input_ids', 'token_type_ids', 'attention_mask', 'labels'], inputs)}

    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature
        loss = F.kl_div(F.log_softmax(student_logits, dim=-1), F.softmax(teacher_logits, dim=-1), reduction="batchmean")

        # Add cross-entropy loss
        loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False

# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True
)

# Initialize the Trainer
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    data_collator=None,  # Default collator works fine
    args=training_args,
    temperature=10.0,
)

# Train the model
trainer.train()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

NameError: name 'inputs' is not defined

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

# Create PyTorch datasets
tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)

# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature
        loss = F.kl_div(F.log_softmax(student_logits, dim=-1), F.softmax(teacher_logits, dim=-1), reduction="batchmean")

        # Add cross-entropy loss
        loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False

# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True,
)

# Initialize the Trainer
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    #data_collator=None,  # Default collator works fine
    args=training_args,
    temperature=10.0,
)

# Train the model
trainer.train()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

TypeError: vars() argument must have __dict__ attribute

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

# Create PyTorch datasets
tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)

# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature
        loss = F.kl_div(F.log_softmax(student_logits, dim=-1), F.softmax(teacher_logits, dim=-1), reduction="batchmean")

        # Add cross-entropy loss
        loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False

# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True,
)

# Initialize the Trainer
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    #data_collator=None,  # Default collator works fine
    args=training_args,
    temperature=10.0,
)

# Train the model
trainer.train()

Mounted at /content/drive

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

TypeError: vars() argument must have __dict__ attribute

In [ ]:
"""Chat history


ChatGPT
ChatGPT
GPT
Humanize AI
GPT
AI Humanizer

Explore GPTs
Today
BERT Model Data Processing

Chemical vs Physical Properties
Chemical vs Physical Changes
Aws Discussion on Iceberg
Out of Office Message
Yesterday
Follow-Up Email Request
Array Slice Error
Previous 7 Days
Concurrent Validity vs Reliability
Form Submission Issue
Locating Data Engine Logs
Databricks Azure Migration Query
Protein Content Inquiry
Fridge Replacement Check Update
Cost Report Clarification
Access Restoration and Permissions
AAD Group Access Improvement
Cost of Data Ingestion
Previous 30 Days
Sentiment Model Help
Face-Framing Layers Tips
Time Off Request Notification
Time Off Request Update
Out-of-Office Notification
Study Spots After 5
Hypothalamus Functions Overview
Anonymous File Upload Methods
Chyme CCK Role
Protein and Muscle Building
Patching Schedule Request
Add Team workspace
Collaborate on a Team plan
ChatGPT 4o


User
You said:
"""
import tf_keras as tfk
import gensim.downloader as api
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tf_keras import models as md
from tf_keras import layers as ly
from tf_keras import losses as ls
from tf_keras import optimizers as oz
from tf_keras import metrics as ms
import numpy as np
import tensorflow as tf
# import drive
# import files
# from datasets import Dataset
from transformers import (BertTokenizerFast, TFBertTokenizer, BertTokenizer, RobertaTokenizerFast,
                          DataCollatorWithPadding, TFRobertaForSequenceClassification, TFBertForSequenceClassification,
                          TFBertModel, create_optimizer)
import torch, pathlib, os, re, string, time
from torch import tensor
import pandas as
import transformers as trf
from transformers import AutoConfig

from google.colab import drive

import accelerate
from tf_keras.src.losses import kl_divergence
from transformers import Trainer, TrainingArguments
from tf_keras.src.optimizers.adam import Adam

import pickle

from tf_keras.src.optimizers.schedules.learning_rate_schedule import CosineDecay

import torch
from torch.utils.data import TensorDataset


from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
dataset2 = pd.read_parquet(r"/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet(r"/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

cdataset2 = dataset2
dataset2_text = dataset2["text"].tolist()
dataset3_text = dataset3["text"].tolist()
cdataset3 = dataset3
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig

tokenizer = BertTokenizerFast.from_pretrained(model_max_length=1024, pretrained_model_name_or_path='bert-base-uncased')
config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
tdataset2_text = tokenizer(dataset2_text, padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3_text, padding=True, truncation=True, max_length=128)
tdataset2_dict = tdataset2_text.data
tdataset3_dict = tdataset3_text.data
cTdataset2 = pd.DataFrame.from_dict(tdataset2_dict)

cdataset2 = pd.concat([cdataset2, cTdataset2], axis=1)
tokenized_dataset2 = cdataset2

cTdataset3 = pd.DataFrame.from_dict(tdataset3_dict)

cdataset3 = pd.concat([cdataset3, cTdataset3], axis=1)
tokenized_dataset3 = cdataset3

print(cdataset2.shape)
print(cdataset2.columns)
print(len(cdataset2['input_ids']), len(cdataset2['token_type_ids']), len(cdataset2['attention_mask']), len(cdataset2['label']))
print(cdataset3.shape)
print(cdataset3.columns)
print(len(cdataset3['input_ids']), len(cdataset3['token_type_ids']), len(cdataset3['attention_mask']), len(cdataset3['label']))



BATCH_SIZE=8
numeric_feature_ames2 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features2 = tokenized_dataset2[numeric_feature_names2]

numeric_feature_names3 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features3 = tokenized_dataset3[numeric_feature_names3]

nf2l = numeric_features2["label"].values.tolist()
nf3l = numeric_features3["label"].values.tolist()
labels2 = torch.tensor(nf2l)
labels3 = torch.tensor(nf3l)

print(labels2.shape, labels2.size())
print(labels3.shape, labels3.size())

import torch.nn.utils.rnn as rnn


# Pad the lists to a fixed length
max_length = 128  # adjust this to the maximum length of your lists
padded_numeric_features2_id = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['input_ids']],
                                               batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_id = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['input_ids']],
                                               batch_first=True)  # , maxlen=max_length)
padded_numeric_features2_ids = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['token_type_ids']],
                                                batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_ids = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['token_type_ids']],
                                                batch_first=True)  # , maxlen=max_length)
padded_numeric_features2_mask = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['attention_mask']],
                                                 batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_mask = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['attention_mask']],
                                                 batch_first=True)  # , maxlen=max_length)
# Convert the padded tensors to PyTorch tensors
import torch.nn.functional as F

padded_numeric_features2_id = F.pad(padded_numeric_features2_id, (0, max_length - padded_numeric_features2_id.shape[1]))
padded_numeric_features3_id = F.pad(padded_numeric_features3_id, (0, max_length - padded_numeric_features3_id.shape[1]))
padded_numeric_features2_ids = F.pad(padded_numeric_features2_ids,
                                     (0, max_length - padded_numeric_features2_ids.shape[1]))
padded_numeric_features3_ids = F.pad(padded_numeric_features3_ids,
                                     (0, max_length - padded_numeric_features3_ids.shape[1]))
padded_numeric_features2_mask = F.pad(padded_numeric_features2_mask,
                                      (0, max_length - padded_numeric_features2_mask.shape[1]))
padded_numeric_features3_mask = F.pad(padded_numeric_features3_mask,
                                      (0, max_length - padded_numeric_features3_mask.shape[1]))


print(padded_numeric_features2_id.shape, padded_numeric_features2_ids.shape, padded_numeric_features2_mask.shape, labels2.shape)
print(padded_numeric_features3_id.size(), padded_numeric_features3_ids.size(), padded_numeric_features3_mask.size(), labels3.size())
#print(tensor_dataset3.get_shape())
#print(type((padded_numeric_features2_id), type(padded_numeric_features2_ids), type( padded_numeric_features2_mask), type(labels2)))
print(type(padded_numeric_features3_id), type(padded_numeric_features3_ids), type(padded_numeric_features3_mask), type(labels3))
#tensor_dataset3 = TensorDataset(padded_numeric_features3_id, padded_numeric_features3_ids, padded_numeric_features3_mask, labels3)
#print(tensor_dataset3['input_ids'].size(), tensor_dataset3['token_type_ids'].size(), tensor_dataset3['attention_mask'].size(), tensor_dataset3['label'].size())
#print(tensor_dataset3.get_shape())

from torch.utils.data import DataLoader

tensor_dataset3 = TensorDataset(padded_numeric_features3_id, padded_numeric_features3_ids, padded_numeric_features3_mask, labels3)

data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE)



# Get the shape and size of each tensor in the dataset
print(tensor_dataset3.tensors[0].shape)  # shape of padded_numeric_features3_id
print(tensor_dataset3.tensors[0].size())  # size of padded_numeric_features3_id

print(tensor_dataset3.tensors[1].shape)  # shape of padded_numeric_features3_ids
print(tensor_dataset3.tensors[1].size())  # size of padded_numeric_features3_ids

print(tensor_dataset3.tensors[2].shape)  # shape of padded_numeric_features3_mask
print(tensor_dataset3.tensors[2].size())  # size of padded_numeric_features3_mask

print(tensor_dataset3.tensors[3].shape)  # shape of labels3
print(tensor_dataset3.tensors[3].size())  # size of labels3
# Create a pandas DataFrame from the DataLoader
df3 = pd.DataFrame([batch for batch in data_loader3])

# Assign column names
df3.columns = ['input_ids', 'token_type_ids', 'attention_mask', 'label']




import torch
from torch.utils.data import Dataset, DataLoader

#print(len(labels2), len(input_ids2), len(attention_mask2), len(token_type_ids2))
print(len(labels3), len(padded_numeric_features3_id), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask))

class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels
        self.field_names = ['input_ids', 'token_type_ids', 'attention_mask', 'labels']

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }


# Assuming df is your pandas DataFrame
input_ids3 = [tensor for tensor in df3['input_ids']]
token_type_ids3 = [tensor for tensor in df3['token_type_ids']]
attention_mask3 = [tensor for tensor in df3['attention_mask']]
labels3 = df3['label'].values

#print(input_ids3.shape, token_type_ids3.shape, padded_numeric_features3_ids.shape, padded_numeric_features3_mask.shape, len(labels3))
print(len(input_ids3), len(token_type_ids3), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask), len(labels3))


try:
    datasetxxx3 = CustomTensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)
    data_loaderxx3 = DataLoader(datasetxxx3, batch_size=8, shuffle=True)
except Exception as e:
    print(f"Error creating datasetxxx3: {e}")

tensor_dataset2 = TensorDataset(padded_numeric_features2_id, padded_numeric_features2_ids,
                                padded_numeric_features2_mask, labels2)
from torch.utils.data import DataLoader

data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE)





# Create a pandas DataFrame from the DataLoader
df2 = pd.DataFrame([batch for batch in data_loader2])

# Assign column names
df2.columns = ['input_ids', 'token_type_ids', 'attention_mask', 'label']

import torch
from torch.utils.data import Dataset, DataLoader


class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels
        self.field_names = ['input_ids', 'token_type_ids', 'attention_mask', 'labels']

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }


# Assuming df is your pandas DataFrame
input_ids2 = [tensor for tensor in df2['input_ids']]
token_type_ids2 = [tensor for tensor in df2['token_type_ids']]
attention_mask2 = [tensor for tensor in df2['attention_mask']]
labels2 = df2['label'].values

#print(input_ids3.shape, token_type_ids3.shape, padded_numeric_features3_ids.shape, padded_numeric_features3_mask.shape, len(labels3))
print(len(input_ids2), len(token_type_ids2), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask), len(labels2))

try:
    datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
    data_loaderxx2 = DataLoader(datasetxxx2, batch_size=8, shuffle=True)
except Exception as e:
    print(f"Error creating datasetxxx2: {e}")

"""
datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)

# Create a DataLoader from the custom dataset
data_loaderxx2 = DataLoader(datasetxxx2, batch_size=8, shuffle=True)"""

print(df2.shape, df2.columns)
print(df3.shape, df3.columns)


# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased',num_labels=1)
# model = AutoModelForSequenceClassification.from_scratch(num_labels=1)
# model = AutoModelForSequenceClassification(config=AutoConfig(num_labels=1))

# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased', num_labels=1)

#config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
config.num_labels = 1

model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False

model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True
"""

print(len(input_ids2), len(token_type_ids2), len(attention_mask2), len(labels2))
datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
"""
from transformers import TrainingArguments, Trainer
import torch
import torch.nn as nn
import torch.nn.functional as F



class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, train_dataset=None, eval_dataset=None, temperature=None, compute_metrics=None, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.student = student_model
        # self.loss_function = nn.KLDivLoss(reduction="batchmean")
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.teacher.to(device)
        self.teacher.eval()
        self.temperature = temperature
        #teacher_model = teacher_model,  # the model to be trained
        #student_model=student_model,
        #args = training_args,  # training arguments
        self.train_dataset = train_dataset,  # training dataset
        self.eval_dataset = eval_dataset,  # evaluation dataset
        self.compute_metrics = compute_metrics


    def get_logits(inputs):
        teacher_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        student_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        teacher_logits = teacher_model(**teacher_inputs).logits
        student_logits = student_model(**student_inputs).logits
        return teacher_logits, student_logits


    def distillation_loss(teacher_logits, student_logits, temperature=10.0):
        teacher_probs = tf.nn.softmax(teacher_logits / temperature, axis=-1)
        student_probs = tf.nn.softmax(student_logits / temperature, axis=-1)
        return kl_divergence()(teacher_probs, student_probs)


    def compute_loss(model, inputs):
        teacher_logits, student_logits = get_logits(inputs)
        loss = distillation_loss(teacher_logits, student_logits)
        return loss





# ===============================================================================================================================

# from transformers import AutoModelForImageClassification, MobileNetV2Config, MobileNetV2ForImageClassification

training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    # total # of training epochs
    # prediction_loss_only=compute_loss,
    per_device_train_batch_size=8,  # batch size
    # per device during training
    per_device_eval_batch_size=8,  # batch size for evaluation
    warmup_steps=500,  # number of warmup steps for learning rate scheduler
    weight_decay=0.01,
)

# =============================================================================================================================

num_epochs = 3
batches_per_epoch = 1  # 227(1821)[07196]69170,8
total_train_steps = int(batches_per_epoch * num_epochs)
# optimizer = Adam(init_lr=2e-5)#, num_warmup_steps=0, num_train_steps=total_train_steps)
optimizer = Adam()
scheduler = CosineDecay(initial_learning_rate=2e-5, decay_steps=total_train_steps)

####
from transformers import DataCollatorWithPadding, DataCollator


import torch
from transformers import AutoModelForSequenceClassification, AutoConfig, TrainingArguments, Trainer
from torch.utils.data import Dataset, DataLoader


# Define the custom data collator function
def custom_data_collator(features):
    input_ids = torch.tensor([f['input_ids'] for f in features])
    token_type_ids = torch.tensor([f['token_type_ids'] for f in features])
    attention_mask = torch.tensor([f['attention_mask'] for f in features])
    labels = torch.tensor([f['labels'] for f in features])

    return {
        'input_ids': input_ids,
        'token_type_ids': token_type_ids,
        'attention_mask': attention_mask,
        'labels': labels
    }

# Define the ImageDistilTrainer class

# Define the training arguments
training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    #num_train_epochs
	  num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
)

# Load the pre-trained BERT model and tokenizer
#tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
"""
config = AutoConfig.from_pretrained('bert-base-uncased')
config.num_labels = 1
model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False
model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True
"""
# Create the ImageDistilTrainer instance
trainer = ImageDistilTrainer(
    student_model=model,
    teacher_model=model,
    train_dataset=datasetxxx2,
    eval_dataset=datasetxxx3,
    data_collator=custom_data_collator,
    compute_metrics=lambda pred: {'accuracy': torch.sum(pred.label_ids == pred.predictions.argmax(-1))},
    temperature=10,
)

# Train the model
trainer.train()

#################################the above is my code for knowledge distilaation bert to bert (self), now waht should be tha appropriate code, taht no erros is faced.
ChatGPT said:
ChatGPT
Your code involves setting up a knowledge distillation framework where a student BERT model is trained by distilling knowledge from a teacher BERT model. However, there are a few issues and best practices that can help improve your implementation and avoid errors. Here's an appropriate version of your code, cleaned up and organized for better clarity and functionality:

python
Copy code
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          AutoConfig, Trainer, TrainingArguments)

# Load the data
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
dataset2 = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

# Tokenize the data
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tdataset2_text = tokenizer(dataset2["text"].tolist(), padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3["text"].tolist(), padding=True, truncation=True, max_length=128)

# Create PyTorch tensors
labels2 = torch.tensor(dataset2['label'].values)
labels3 = torch.tensor(dataset3['label'].values)

input_ids2 = torch.tensor(tdataset2_text['input_ids'])
token_type_ids2 = torch.tensor(tdataset2_text['token_type_ids'])
attention_mask2 = torch.tensor(tdataset2_text['attention_mask'])

input_ids3 = torch.tensor(tdataset3_text['input_ids'])
token_type_ids3 = torch.tensor(tdataset3_text['token_type_ids'])
attention_mask3 = torch.tensor(tdataset3_text['attention_mask'])

# Create PyTorch datasets
tensor_dataset2 = TensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
tensor_dataset3 = TensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)

# Create DataLoaders
BATCH_SIZE = 8
data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE, shuffle=True)
data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE, shuffle=False)

# Define the custom Trainer class
class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, temperature=1.0, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False):
        student_outputs = model(**inputs)
        with torch.no_grad():
            teacher_outputs = self.teacher(**inputs)

        # Calculate distillation loss
        student_logits = student_outputs.logits / self.temperature
        teacher_logits = teacher_outputs.logits / self.temperature
        loss = F.kl_div(F.log_softmax(student_logits, dim=-1), F.softmax(teacher_logits, dim=-1), reduction="batchmean")

        # Add cross-entropy loss
        loss += F.cross_entropy(student_logits, inputs['labels'])

        return (loss, student_outputs) if return_outputs else loss

# Load the models
config = AutoConfig.from_pretrained('bert-base-uncased', num_labels=1)
student_model = AutoModelForSequenceClassification.from_config(config)
teacher_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

# Freeze teacher model
for param in teacher_model.parameters():
    param.requires_grad = False

# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/output",
    num_train_epochs=3,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir="/content/drive/MyDrive/logging",
    logging_strategy="epoch",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=True,
)

# Initialize the Trainer
trainer = ImageDistilTrainer(
    student_model=student_model,
    teacher_model=teacher_model,
    train_dataset=tensor_dataset2,
    eval_dataset=tensor_dataset3,
    data_collator=None,  # Default collator works fine
    args=training_args,
    temperature=10.0,
)

# Train the model
trainer.train()
Key Adjustments:
Correct compute_loss Implementation: The compute_loss method correctly implements the distillation loss by calculating the KL divergence between the teacher and student logits and adding cross-entropy loss.

Simplified Dataset Handling: The TensorDataset and DataLoader structures are simplified and directly created from the tokenized datasets.

Model and Training Setup: The teacher model's weights are frozen to ensure that only the student model is trained. The configuration for training is simplified with TrainingArguments.

Custom Trainer Class: A custom Trainer class (ImageDistilTrainer) is used to handle the specific logic required for knowledge distillation.

This code should run without errors, provided that the necessary packages are correctly installed and the environment is properly set up.









Message ChatGPT

ChatGPT can make mistakes. Check important info.
?

SyntaxError: invalid decimal literal (<ipython-input-1-16464fb150f7>, line 47)

In [ ]:

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
dataset2 = pd.read_parquet(r"/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")

ValueError: mount failed

In [ ]:
import tf_keras as tfk
import gensim.downloader as api
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tf_keras import models as md
from tf_keras import layers as ly
from tf_keras import losses as ls
from tf_keras import optimizers as oz
from tf_keras import metrics as ms
import numpy as np
import tensorflow as tf
# import drive
# import files
# from datasets import Dataset
from transformers import (BertTokenizerFast, TFBertTokenizer, BertTokenizer, RobertaTokenizerFast,
                          DataCollatorWithPadding, TFRobertaForSequenceClassification, TFBertForSequenceClassification,
                          TFBertModel, create_optimizer)
import torch, pathlib, os, re, string, time
from torch import tensor
import pandas as pd
import transformers as trf
from transformers import AutoConfig

from google.colab import drive

import accelerate
from tf_keras.src.losses import kl_divergence
from transformers import Trainer, TrainingArguments
from tf_keras.src.optimizers.adam import Adam

import pickle

from tf_keras.src.optimizers.schedules.learning_rate_schedule import CosineDecay

import torch
from torch.utils.data import TensorDataset


from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
dataset2 = pd.read_parquet(r"/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet(r"/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

cdataset2 = dataset2
dataset2_text = dataset2["text"].tolist()
dataset3_text = dataset3["text"].tolist()
cdataset3 = dataset3
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig

tokenizer = BertTokenizerFast.from_pretrained(model_max_length=1024, pretrained_model_name_or_path='bert-base-uncased')
config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
tdataset2_text = tokenizer(dataset2_text, padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3_text, padding=True, truncation=True, max_length=128)
tdataset2_dict = tdataset2_text.data
tdataset3_dict = tdataset3_text.data
cTdataset2 = pd.DataFrame.from_dict(tdataset2_dict)

cdataset2 = pd.concat([cdataset2, cTdataset2], axis=1)
tokenized_dataset2 = cdataset2

cTdataset3 = pd.DataFrame.from_dict(tdataset3_dict)

cdataset3 = pd.concat([cdataset3, cTdataset3], axis=1)
tokenized_dataset3 = cdataset3

print(cdataset2.shape)
print(cdataset2.columns)
print(len(cdataset2['input_ids']), len(cdataset2['token_type_ids']), len(cdataset2['attention_mask']), len(cdataset2['label']))
print(cdataset3.shape)
print(cdataset3.columns)
print(len(cdataset3['input_ids']), len(cdataset3['token_type_ids']), len(cdataset3['attention_mask']), len(cdataset3['label']))



BATCH_SIZE=8
numeric_feature_ames2 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features2 = tokenized_dataset2[numeric_feature_names2]

numeric_feature_names3 = ['input_ids', 'token_type_ids', 'attention_mask', 'label']
numeric_features3 = tokenized_dataset3[numeric_feature_names3]

nf2l = numeric_features2["label"].values.tolist()
nf3l = numeric_features3["label"].values.tolist()
labels2 = torch.tensor(nf2l)
labels3 = torch.tensor(nf3l)

print(labels2.shape, labels2.size())
print(labels3.shape, labels3.size())

import torch.nn.utils.rnn as rnn


# Pad the lists to a fixed length
max_length = 128  # adjust this to the maximum length of your lists
padded_numeric_features2_id = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['input_ids']],
                                               batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_id = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['input_ids']],
                                               batch_first=True)  # , maxlen=max_length)
padded_numeric_features2_ids = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['token_type_ids']],
                                                batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_ids = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['token_type_ids']],
                                                batch_first=True)  # , maxlen=max_length)
padded_numeric_features2_mask = rnn.pad_sequence([torch.tensor(x) for x in numeric_features2['attention_mask']],
                                                 batch_first=True)  # , maxlen=max_length)
padded_numeric_features3_mask = rnn.pad_sequence([torch.tensor(x) for x in numeric_features3['attention_mask']],
                                                 batch_first=True)  # , maxlen=max_length)
# Convert the padded tensors to PyTorch tensors
import torch.nn.functional as F

padded_numeric_features2_id = F.pad(padded_numeric_features2_id, (0, max_length - padded_numeric_features2_id.shape[1]))
padded_numeric_features3_id = F.pad(padded_numeric_features3_id, (0, max_length - padded_numeric_features3_id.shape[1]))
padded_numeric_features2_ids = F.pad(padded_numeric_features2_ids,
                                     (0, max_length - padded_numeric_features2_ids.shape[1]))
padded_numeric_features3_ids = F.pad(padded_numeric_features3_ids,
                                     (0, max_length - padded_numeric_features3_ids.shape[1]))
padded_numeric_features2_mask = F.pad(padded_numeric_features2_mask,
                                      (0, max_length - padded_numeric_features2_mask.shape[1]))
padded_numeric_features3_mask = F.pad(padded_numeric_features3_mask,
                                      (0, max_length - padded_numeric_features3_mask.shape[1]))


print(padded_numeric_features2_id.shape, padded_numeric_features2_ids.shape, padded_numeric_features2_mask.shape, labels2.shape)
print(padded_numeric_features3_id.size(), padded_numeric_features3_ids.size(), padded_numeric_features3_mask.size(), labels3.size())
#print(tensor_dataset3.get_shape())
#print(type((padded_numeric_features2_id), type(padded_numeric_features2_ids), type( padded_numeric_features2_mask), type(labels2)))
print(type(padded_numeric_features3_id), type(padded_numeric_features3_ids), type(padded_numeric_features3_mask), type(labels3))
#tensor_dataset3 = TensorDataset(padded_numeric_features3_id, padded_numeric_features3_ids, padded_numeric_features3_mask, labels3)
#print(tensor_dataset3['input_ids'].size(), tensor_dataset3['token_type_ids'].size(), tensor_dataset3['attention_mask'].size(), tensor_dataset3['label'].size())
#print(tensor_dataset3.get_shape())

from torch.utils.data import DataLoader

tensor_dataset3 = TensorDataset(padded_numeric_features3_id, padded_numeric_features3_ids, padded_numeric_features3_mask, labels3)

data_loader3 = DataLoader(tensor_dataset3, batch_size=BATCH_SIZE)



# Get the shape and size of each tensor in the dataset
print(tensor_dataset3.tensors[0].shape)  # shape of padded_numeric_features3_id
print(tensor_dataset3.tensors[0].size())  # size of padded_numeric_features3_id

print(tensor_dataset3.tensors[1].shape)  # shape of padded_numeric_features3_ids
print(tensor_dataset3.tensors[1].size())  # size of padded_numeric_features3_ids

print(tensor_dataset3.tensors[2].shape)  # shape of padded_numeric_features3_mask
print(tensor_dataset3.tensors[2].size())  # size of padded_numeric_features3_mask

print(tensor_dataset3.tensors[3].shape)  # shape of labels3
print(tensor_dataset3.tensors[3].size())  # size of labels3
# Create a pandas DataFrame from the DataLoader
df3 = pd.DataFrame([batch for batch in data_loader3])

# Assign column names
df3.columns = ['input_ids', 'token_type_ids', 'attention_mask', 'label']




import torch
from torch.utils.data import Dataset, DataLoader

#print(len(labels2), len(input_ids2), len(attention_mask2), len(token_type_ids2))
print(len(labels3), len(padded_numeric_features3_id), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask))

class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels
        self.field_names = ['input_ids', 'token_type_ids', 'attention_mask', 'labels']

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }


# Assuming df is your pandas DataFrame
input_ids3 = [tensor for tensor in df3['input_ids']]
token_type_ids3 = [tensor for tensor in df3['token_type_ids']]
attention_mask3 = [tensor for tensor in df3['attention_mask']]
labels3 = df3['label'].values

#print(input_ids3.shape, token_type_ids3.shape, padded_numeric_features3_ids.shape, padded_numeric_features3_mask.shape, len(labels3))
print(len(input_ids3), len(token_type_ids3), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask), len(labels3))


try:
    datasetxxx3 = CustomTensorDataset(input_ids3, token_type_ids3, attention_mask3, labels3)
    data_loaderxx3 = DataLoader(datasetxxx3, batch_size=8, shuffle=True)
except Exception as e:
    print(f"Error creating datasetxxx3: {e}")

tensor_dataset2 = TensorDataset(padded_numeric_features2_id, padded_numeric_features2_ids,
                                padded_numeric_features2_mask, labels2)
from torch.utils.data import DataLoader

data_loader2 = DataLoader(tensor_dataset2, batch_size=BATCH_SIZE)





# Create a pandas DataFrame from the DataLoader
df2 = pd.DataFrame([batch for batch in data_loader2])

# Assign column names
df2.columns = ['input_ids', 'token_type_ids', 'attention_mask', 'label']

import torch
from torch.utils.data import Dataset, DataLoader


class CustomTensorDataset(Dataset):
    def __init__(self, input_ids, token_type_ids, attention_mask, labels):
        self.input_ids = input_ids
        self.token_type_ids = token_type_ids
        self.attention_mask = attention_mask
        self.labels = labels
        self.field_names = ['input_ids', 'token_type_ids', 'attention_mask', 'labels']

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.input_ids[idx],
            'token_type_ids': self.token_type_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': self.labels[idx]
        }


# Assuming df is your pandas DataFrame
input_ids2 = [tensor for tensor in df2['input_ids']]
token_type_ids2 = [tensor for tensor in df2['token_type_ids']]
attention_mask2 = [tensor for tensor in df2['attention_mask']]
labels2 = df2['label'].values

#print(input_ids3.shape, token_type_ids3.shape, padded_numeric_features3_ids.shape, padded_numeric_features3_mask.shape, len(labels3))
print(len(input_ids2), len(token_type_ids2), len(padded_numeric_features3_ids), len(padded_numeric_features3_mask), len(labels2))

try:
    datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
    data_loaderxx2 = DataLoader(datasetxxx2, batch_size=8, shuffle=True)
except Exception as e:
    print(f"Error creating datasetxxx2: {e}")

"""
datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)

# Create a DataLoader from the custom dataset
data_loaderxx2 = DataLoader(datasetxxx2, batch_size=8, shuffle=True)"""

print(df2.shape, df2.columns)
print(df3.shape, df3.columns)


# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased',num_labels=1)
# model = AutoModelForSequenceClassification.from_scratch(num_labels=1)
# model = AutoModelForSequenceClassification(config=AutoConfig(num_labels=1))

# model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path='bert-base-uncased', num_labels=1)

#config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
config.num_labels = 1

model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False

model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True
"""

print(len(input_ids2), len(token_type_ids2), len(attention_mask2), len(labels2))
datasetxxx2 = CustomTensorDataset(input_ids2, token_type_ids2, attention_mask2, labels2)
"""
from transformers import TrainingArguments, Trainer
import torch
import torch.nn as nn
import torch.nn.functional as F



class ImageDistilTrainer(Trainer):
    def __init__(self, student_model=None, teacher_model=None, train_dataset=None, eval_dataset=None, temperature=None, compute_metrics=None, *args, **kwargs):
        super().__init__(model=student_model, *args, **kwargs)
        self.teacher = teacher_model
        self.student = student_model
        # self.loss_function = nn.KLDivLoss(reduction="batchmean")
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.teacher.to(device)
        self.teacher.eval()
        self.temperature = temperature
        #teacher_model = teacher_model,  # the model to be trained
        #student_model=student_model,
        #args = training_args,  # training arguments
        self.train_dataset = train_dataset,  # training dataset
        self.eval_dataset = eval_dataset,  # evaluation dataset
        self.compute_metrics = compute_metrics


    def get_logits(inputs):
        teacher_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        student_inputs = {'input_ids': inputs['input_ids'], 'attention_mask': inputs['attention_mask']}
        teacher_logits = teacher_model(**teacher_inputs).logits
        student_logits = student_model(**student_inputs).logits
        return teacher_logits, student_logits


    def distillation_loss(teacher_logits, student_logits, temperature=10.0):
        teacher_probs = tf.nn.softmax(teacher_logits / temperature, axis=-1)
        student_probs = tf.nn.softmax(student_logits / temperature, axis=-1)
        return kl_divergence()(teacher_probs, student_probs)


    def compute_loss(model, inputs):
        teacher_logits, student_logits = get_logits(inputs)
        loss = distillation_loss(teacher_logits, student_logits)
        return loss





# ===============================================================================================================================

# from transformers import AutoModelForImageClassification, MobileNetV2Config, MobileNetV2ForImageClassification

training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    # total # of training epochs
    # prediction_loss_only=compute_loss,
    per_device_train_batch_size=8,  # batch size
    # per device during training
    per_device_eval_batch_size=8,  # batch size for evaluation
    warmup_steps=500,  # number of warmup steps for learning rate scheduler
    weight_decay=0.01,
)

# =============================================================================================================================

num_epochs = 3
batches_per_epoch = 1  # 227(1821)[07196]69170,8
total_train_steps = int(batches_per_epoch * num_epochs)
# optimizer = Adam(init_lr=2e-5)#, num_warmup_steps=0, num_train_steps=total_train_steps)
optimizer = Adam()
scheduler = CosineDecay(initial_learning_rate=2e-5, decay_steps=total_train_steps)

####
from transformers import DataCollatorWithPadding, DataCollator


import torch
from transformers import AutoModelForSequenceClassification, AutoConfig, TrainingArguments, Trainer
from torch.utils.data import Dataset, DataLoader


# Define the custom data collator function
def custom_data_collator(features):
    input_ids = torch.tensor([f['input_ids'] for f in features])
    token_type_ids = torch.tensor([f['token_type_ids'] for f in features])
    attention_mask = torch.tensor([f['attention_mask'] for f in features])
    labels = torch.tensor([f['labels'] for f in features])

    return {
        'input_ids': input_ids,
        'token_type_ids': token_type_ids,
        'attention_mask': attention_mask,
        'labels': labels
    }

# Define the ImageDistilTrainer class

# Define the training arguments
training_args = TrainingArguments(
    output_dir=r"/content/drive/MyDrive",
    #num_train_epochs
	  num_train_epochs=3,
    fp16=True,
    logging_dir=r"/content/drive/MyDrive",
    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
)

# Load the pre-trained BERT model and tokenizer
#tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
"""
config = AutoConfig.from_pretrained('bert-base-uncased')
config.num_labels = 1
model = AutoModelForSequenceClassification.from_config(config)
model.init_weights()
for param in model.bert.parameters():
    param.requires_grad = False
model.classifier.weight.requires_grad = True
model.classifier.bias.requires_grad = True
"""
# Create the ImageDistilTrainer instance
trainer = ImageDistilTrainer(
    student_model=model,
    teacher_model=model,
    train_dataset=datasetxxx2,
    eval_dataset=datasetxxx3,
    data_collator=custom_data_collator,
    compute_metrics=lambda pred: {'accuracy': torch.sum(pred.label_ids == pred.predictions.argmax(-1))},
    temperature=10,
)

# Train the model
trainer.train()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
(9543, 5)
Index(['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'], dtype='object')
9543 9543 9543 9543
(2388, 5)
Index(['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'], dtype='object')
2388 2388 2388 2388
torch.Size([9543]) torch.Size([9543])
torch.Size([2388]) torch.Size([2388])
torch.Size([9543, 128]) torch.Size([9543, 128]) torch.Size([9543, 128]) torch.Size([9543])
torch.Size([2388, 128]) torch.Size([2388, 128]) torch.Size([2388, 128]) torch.Size([2388])
torch.Size([2388, 128])
torch.Size([2388, 128])
torch.Size([2388, 128])
torch.Size([2388, 128])
torch.Size([2388, 128])
torch.Size([2388, 128])
torch.Size([2388])
torch.Size([2388])
2388 2388 2388 2388
299 299 2388 2388 299
1193 1193 2388 2388 1193
(1193, 4) Index(['input_ids', 'token_type_ids', 'attention_mask', 'label'], dtype='object')
(299, 4) Index(['input_ids', 'token_type_ids', 'attention_mask', 'label'], dtype='object')

TypeError: list indices must be integers or slices, not str

In [ ]:
j=9

In [ ]:
from huggingface_hub import login
hf_token = "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"
login(hf_token)
import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(student_model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
        index, row = batch
        text2 = row.values
        text = text2[0]
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))

    # result = roberta_result | bert_result
    return result


# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(student_model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
        index, row = batch
        text2 = row.values
        text = text2[0]
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))

    # result = roberta_result | bert_result
    return result


# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

ValueError: mount failed

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device
from torch.utils.data import DataLoader


# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss(reduction='batchmean')(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")
dataloader = DataLoader(df, batch_size=16, shuffle=True)
optim = torch.optim.AdamW(student_model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    accumulation_steps = 4
    optim.zero_grad()
    for i, batch in enumerate(dataloader):
        input_ids, attention_mask = batch['input_ids'], batch['attention_mask']
        student_output = student_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask).logits.detach()

        loss = knowledge_distillation_loss(student_output, teacher_output)
        loss = loss / accumulation_steps  # Normalize loss
        loss.backward()

        if (i + 1) % accumulation_steps == 0:
            optim.step()
            optim.zero_grad()

    """
    for batch in tqdm(df.iterrows(), total=len(df)):
        index, row = batch
        text2 = row.values
        text = text2[0]
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()
    """
import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    #input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True, clean_up_tokenization_spaces=True)
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))

    # result = roberta_result | bert_result
    return result


# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(student_model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
        index, row = batch
        text2 = row.values
        text = text2[0]
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))

    # result = roberta_result | bert_result
    return result


# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

  0%|          | 0/9543 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py:2994: UserWarning: reduction: 'mean' divides the total loss by both the batch size and the support size.'batchmean' divides only by the batch size, and aligns with the KL div math definition.'mean' will be changed to behave the same as 'batchmean' in the next major release.
  warnings.warn(
 79%|███████▊  | 7501/9543 [3:06:39<53:46,  1.58s/it]

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(student_model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
		    index, row = batch
        text2 = row.values
		    text= text2[0]
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))


    # result = roberta_result | bert_result
    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 48)

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(student_model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
		index, row = batch
        text2 = row.values
		text= text2[0]
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))


    # result = roberta_result | bert_result
    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 48)

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(student_model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
		    index, row = batch
        text2 = row.values
		    text= text2[0]
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))


    # result = roberta_result | bert_result
    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 48)

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(student_model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
		    index, fow = batch
        text2 = fow.values
		    text= text2[0]
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))


    # result = roberta_result | bert_result
    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

In [ ]:
import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

# Load the teacher model (RoBERTa or BERT)
model_name='roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
#dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
        text = batch['review_text']
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer

def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores

def rating_prediction_bert(text):
	# Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)#####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores

# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy() ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
	  result = np.concatenate((roberta_result, bert_result))
    #result = roberta_result | bert_result

    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)


"""
This code defines a new function predict_sentiment_and_rating that uses the student model to perform sentiment analysis and rating prediction. It takes in a text input, encodes it using the student tokenizer, and passes it through the student model to get the output. The output is then processed to get the sentiment scores and rating prediction, which are combined into a single dictionary.

The code then tests the student model on two example texts, printing out the results.

Note that this is just a basic example, and you may need to fine-tune the hyperparameters and experiment with different knowledge distillation techniques to achieve the best results.

Also, keep in mind that knowledge distillation is a complex topic, and this code is just a starting point. You may need to modify the code to suit your specific use case and experiment with different approaches to achieve the best results.

Let me know if you have any questions or need further assistance!




New Chat

Follow
Scroll to bottom
"""

TabError: inconsistent use of tabs and spaces in indentation (<ipython-input-7-2ea5fcf35401>, line 116)

In [ ]:
j=7

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
        text = batch['review_text']
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))


    # result = roberta_result | bert_result
    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(student_model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
        text = batch[idx]
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))


    # result = roberta_result | bert_result
    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(student_model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
        text = batch['review_text']
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))


    # result = roberta_result | bert_result
    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

  0%|          | 0/9543 [00:00<?, ?it/s]

TypeError: tuple indices must be integers or slices, not str

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(student_model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
        text = batch['review_text']
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))


    # result = roberta_result | bert_result
    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Mounted at /content/drive

NameError: name 'model' is not defined

In [ ]:

import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
from torch import device



# Load the teacher model (RoBERTa or BERT)
model_name = 'roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
# dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
        text = batch['review_text']
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()  ###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits  ####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer


def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


def rating_prediction_bert(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)  #####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores


# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()  ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = np.concatenate((roberta_result, bert_result))


    # result = roberta_result | bert_result
    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)

NameError: name 'teacher_model' is not defined

In [ ]:
import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
from torch import nn
from torch.nn import KLDivLoss
from torch.nn.functional import softmax
from torch.nn import functional
import pandas as pd
import pandas as pd
import numpy as np
from scipy.special import softmax
import csv
import urllib.request

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
teacher_model.to(device)
student_model.to(device)

# Load the teacher model (RoBERTa or BERT)
model_name='roberta-base'
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)


from google.colab import drive

drive.mount('/content/drive')
df = pd.read_parquet("/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
#dataset3 = pd.read_parquet("/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

optim = torch.optim.AdamW(model.parameters(), lr=1e-5)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
        text = batch['review_text']
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()###################################

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits####################

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optim.step()

import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer

def polarity_scores_roberta(text):
    # Load the RoBERTa model and tokenizer
    roberta_model = RobertaForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores

def rating_prediction_bert(text):
	# Load the RoBERTa model and tokenizer
    roberta_model = DistilBertForSequenceClassification.from_pretrained('roberta-base')
    roberta_tokenizer = DistilBertTokenizer.from_pretrained('roberta-base')

    # Encode the input text
    input_ids = roberta_tokenizer.encode(text, return_tensors='pt')
    attention_mask = roberta_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)

    # Get the sentiment scores
    output = roberta_model(input_ids, attention_mask=attention_mask)

    scores = torch.nn.functional.softmax(output.logits, dim=1)#####################################

    sentiment_scores = scores.detach().numpy()[0]

    return sentiment_scores

# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=512, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy() ########################

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
	  result = np.concatenate((roberta_result, bert_result))
    #result = roberta_result | bert_result

    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)


"""
This code defines a new function predict_sentiment_and_rating that uses the student model to perform sentiment analysis and rating prediction. It takes in a text input, encodes it using the student tokenizer, and passes it through the student model to get the output. The output is then processed to get the sentiment scores and rating prediction, which are combined into a single dictionary.

The code then tests the student model on two example texts, printing out the results.

Note that this is just a basic example, and you may need to fine-tune the hyperparameters and experiment with different knowledge distillation techniques to achieve the best results.

Also, keep in mind that knowledge distillation is a complex topic, and this code is just a starting point. You may need to modify the code to suit your specific use case and experiment with different approaches to achieve the best results.

Let me know if you have any questions or need further assistance!




New Chat

Follow
Scroll to bottom
"""

TabError: inconsistent use of tabs and spaces in indentation (<ipython-input-6-688823d0f555>, line 116)

In [ ]:
import pandas as pd
dataset2 = pd.read_parquet(r"/content/drive/MyDrive/default_train_0000.parquet", engine="pyarrow")
dataset3 = pd.read_parquet(r"/content/drive/MyDrive/default_validation_0000.parquet", engine="pyarrow")

cdataset2 = dataset2
dataset2_text = dataset2["text"].tolist()
dataset3_text = dataset3["text"].tolist()
cdataset3 = dataset3
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig

tokenizer = BertTokenizerFast.from_pretrained(model_max_length=1024, pretrained_model_name_or_path='bert-base-uncased')
config = AutoConfig.from_pretrained(pretrained_model_name_or_path='bert-base-uncased')
tdataset2_text = tokenizer(dataset2_text, padding=True, truncation=True, max_length=128)
tdataset3_text = tokenizer(dataset3_text, padding=True, truncation=True, max_length=128)
tdataset2_dict = tdataset2_text.data
tdataset3_dict = tdataset3_text.data
cTdataset2 = pd.DataFrame.from_dict(tdataset2_dict)

cdataset2 = pd.concat([cdataset2, cTdataset2], axis=1)
tokenized_dataset2 = cdataset2

cTdataset3 = pd.DataFrame.from_dict(tdataset3_dict)

cdataset3 = pd.concat([cdataset3, cTdataset3], axis=1)
tokenized_dataset3 = cdataset3

print(cdataset2.shape)
print(cdataset2.columns)
print(len(cdataset2['input_ids']), len(cdataset2['token_type_ids']), len(cdataset2['attention_mask']), len(cdataset2['label']))
print(cdataset3.shape)
print(cdataset3.columns)
print(len(cdataset3['input_ids']), len(cdataset3['token_type_ids']), len(cdataset3['attention_mask']), len(cdataset3['label']))

In [ ]:
j=9

In [ ]:
import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm

# Load the teacher model (RoBERTa or BERT)
teacher_model = AutoModelForSequenceClassification.from_pretrained(model_name)
teacher_tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the student model (DistilBERT)
student_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
student_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Define a knowledge distillation loss function
def knowledge_distillation_loss(student_output, teacher_output):
    return torch.nn.KLDivLoss()(student_output, teacher_output)

# Train the student model using knowledge distillation
for epoch in range(5):
    for batch in tqdm(df.iterrows(), total=len(df)):
        text = batch['review_text']
        input_ids = student_tokenizer.encode(text, return_tensors='pt')
        attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=514, truncation=True)

        # Get the teacher's output
        teacher_output = teacher_model(input_ids, attention_mask=attention_mask)
        teacher_output = teacher_output.logits.detach()

        # Get the student's output
        student_output = student_model(input_ids, attention_mask=attention_mask)
        student_output = student_output.logits

        # Calculate the knowledge distillation loss
        loss = knowledge_distillation_loss(student_output, teacher_output)

        # Backpropagate and update the student model
        loss.backward()
        optimizer.step()

# Use the student model for sentiment analysis and rating prediction
def predict_sentiment_and_rating(text):
    input_ids = student_tokenizer.encode(text, return_tensors='pt')
    attention_mask = student_tokenizer.encode(text, return_tensors='pt', max_length=514, truncation=True)
    output = student_model(input_ids, attention_mask=attention_mask)
    output = output.logits.detach().numpy()

    # Get the sentiment scores
    roberta_result = polarity_scores_roberta(text)

    # Get the rating prediction
    bert_result = rating_prediction_bert(text)

    # Combine the results
    result = roberta_result | bert_result

    return result

# Test the student model
text = "I love this place! The food is amazing."
result = predict_sentiment_and_rating(text)
print(result)

text = "I'm not a fan of this restaurant. The service is terrible."
result = predict_sentiment_and_rating(text)
print(result)


"""
This code defines a new function predict_sentiment_and_rating that uses the student model to perform sentiment analysis and rating prediction. It takes in a text input, encodes it using the student tokenizer, and passes it through the student model to get the output. The output is then processed to get the sentiment scores and rating prediction, which are combined into a single dictionary.

The code then tests the student model on two example texts, printing out the results.

Note that this is just a basic example, and you may need to fine-tune the hyperparameters and experiment with different knowledge distillation techniques to achieve the best results.

Also, keep in mind that knowledge distillation is a complex topic, and this code is just a starting point. You may need to modify the code to suit your specific use case and experiment with different approaches to achieve the best results.

Let me know if you have any questions or need further assistance!




New Chat

Follow
Scroll to bottom
"""

NameError: name 'AutoModelForSequenceClassification' is not defined